---
version: "{build}"

image: Visual Studio 2022

platform:
  - x64

configuration:
  - release

environment:
  matrix:
    - QT_VERSION: 6.9.3
      QT_ARCH: win64_mingw

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - mkdir C:\Qt
  - py -3 -m pip install --upgrade pip
  - py -3 -m pip install aqtinstall
  - py -3 -m aqt install-qt windows desktop %QT_VERSION% win64_mingw -O C:\Qt
  - set QTDIR=C:\Qt\%QT_VERSION%\mingw_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw1310_64\bin;%PATH%
  - qmake -v
  - mingw32-make -v
  - iscc /?

build_script:
  - qmake qtpass.pro CONFIG+=release CONFIG+=static
  - mingw32-make

  - if exist dist rmdir /s /q dist
  - mkdir dist\qtpass

  - copy src\release\qtpass.exe dist\qtpass\qtpass.exe
  - if not exist dist\qtpass\qtpass.exe exit /b 1

  - windeployqt --release --dir dist\qtpass dist\qtpass\qtpass.exe

  - copy README.md dist\qtpass\README.txt
  - copy LICENSE dist\qtpass\LICENSE.txt
  - if not exist dist\qtpass\README.txt exit /b 1
  - if not exist dist\qtpass\LICENSE.txt exit /b 1

  - dir dist\qtpass

  - if "%APPVEYOR_REPO_TAG%"=="true" (
    iscc /DMyAppVersion=%APPVEYOR_REPO_TAG_NAME% qtpass.iss
    ) else (
    iscc qtpass.iss
    )

artifacts:
  - path: Output\qtpass-*.exe
    name: installer

  - path: dist\qtpass\qtpass.exe
    name: binary
