QtPassSettings
bool QtPassSettings::initialized
QtPassSettings * QtPassSettings::m_instance
Pass * QtPassSettings::pass
QScopedPointer< RealPass > QtPassSettings::realPass
QScopedPointer< ImitatePass > QtPassSettings::imitatePass
QtPassSettings::QtPassSettings()
Private default constructor to enforce singleton usage and prevent direct instantiation.
QtPassSettings::QtPassSettings(const QString &organization, const QSettings::Format format)
QtPassSettings::QtPassSettings(const QString &organization, const QString &application)
QtPassSettings::~QtPassSettings() override=default
QtPassSettings * QtPassSettings::getInstance()
Get the singleton instance.
Pointer to the QtPassSettings instance.
Referenced by getAutoclearPanelSeconds, getAutoclearSeconds, getClipBoardTypeRaw, getDialogGeometry, getDialogPos, getDialogSize, getGeometry, getGitExecutable, getGpgExecutable, getGpgHome, getPassExecutable, getPassSigningKey, getPassStore, getPassTemplate, getPasswordConfiguration, getPos, getProfile, getProfiles, getPwgenExecutable, getQrencodeExecutable, getSavestate, getSize, getVersion, getWebDavPassword, getWebDavUrl, getWebDavUser, isAddGPGId, isAlwaysOnTop, isAutoPull, isAutoPush, isAvoidCapitals, isAvoidNumbers, isDialogMaximized, isDisplayAsIs, isHideContent, isHideOnClose, isHidePassword, isLessRandom, isMaximized, isNoLineWrapping, isStartMinimized, isTemplateAllFields, isUseAutoclear, isUseAutoclearPanel, isUseGit, isUseGrepSearch, isUseMonospace, isUseOtp, isUsePass, isUsePwgen, isUseQrencode, isUseSelection, isUseSymbols, isUseTemplate, isUseTrayIcon, isUseWebDav, setAddGPGId, setAlwaysOnTop, setAutoclearPanelSeconds, setAutoclearSeconds, setAutoPull, setAutoPush, setAvoidCapitals, setAvoidNumbers, setClipBoardType, setDialogGeometry, setDialogMaximized, setDialogPos, setDialogSize, setDisplayAsIs, setGeometry, setGitExecutable, setGpgExecutable, setHideContent, setHideOnClose, setHidePassword, setLessRandom, setMaximized, setNoLineWrapping, setPassExecutable, setPassSigningKey, setPassStore, setPassTemplate, setPasswordChars, setPasswordCharsSelection, setPasswordConfiguration, setPasswordLength, setPos, setProfile, setProfiles, setPwgenExecutable, setQrencodeExecutable, setSavestate, setSize, setStartMinimized, setTemplateAllFields, setUseAutoclear, setUseAutoclearPanel, setUseGit, setUseGrepSearch, setUseMonospace, setUseOtp, setUsePass, setUsePwgen, setUseQrencode, setUseSelection, setUseSymbols, setUseTemplate, setUseTrayIcon, setUseWebDav, setVersion, setWebDavPassword, setWebDavUrl, setWebDavUser.
QString QtPassSettings::getVersion(const QString &defaultValue=QVariant().toString())
Get saved application version.
defaultValue String returned if no version saved. Application version string.
References getInstance, SettingsConstants::version.
Referenced by QtPass::init.
void QtPassSettings::setVersion(const QString &version)
Save application version.
version Version string to save.
References getInstance, SettingsConstants::version.
Referenced by QtPass::init.
QByteArray QtPassSettings::getGeometry(const QByteArray &defaultValue=QVariant().toByteArray())
Get saved window geometry.
defaultValue Byte array returned if no geometry saved. Window geometry as QByteArray.
References SettingsConstants::geometry, getInstance.
Referenced by MainWindow::restoreWindow.
void QtPassSettings::setGeometry(const QByteArray &geometry)
Save window geometry.
geometry Window geometry to save.
References SettingsConstants::geometry, getInstance.
Referenced by MainWindow::closeEvent.
QByteArray QtPassSettings::getSavestate(const QByteArray &defaultValue=QVariant().toByteArray())
Get saved window state.
defaultValue Byte array returned if no state saved. Window state as QByteArray.
References getInstance, SettingsConstants::savestate.
Referenced by MainWindow::restoreWindow.
void QtPassSettings::setSavestate(const QByteArray &saveState)
Save window state.
saveState Window state to save.
References getInstance, SettingsConstants::savestate.
Referenced by MainWindow::closeEvent.
QPoint QtPassSettings::getPos(const QPoint &defaultValue=QVariant().toPoint())
Get saved window position.
defaultValue Point returned if no position saved. Window position as QPoint.
References getInstance, SettingsConstants::pos.
Referenced by MainWindow::restoreWindow.
void QtPassSettings::setPos(const QPoint &pos)
Save window position.
pos Window position to save.
References getInstance, SettingsConstants::pos.
Referenced by MainWindow::closeEvent.
QSize QtPassSettings::getSize(const QSize &defaultValue=QVariant().toSize())
Get saved window size.
defaultValue Size returned if no size saved. Window size as QSize.
References getInstance, SettingsConstants::size.
Referenced by MainWindow::restoreWindow.
void QtPassSettings::setSize(const QSize &size)
Save window size.
size Window size to save.
References getInstance, SettingsConstants::size.
Referenced by MainWindow::closeEvent.
bool QtPassSettings::isMaximized(const bool &defaultValue=QVariant().toBool())
Get maximized state.
defaultValue Boolean returned if not saved. true if window is maximized.
References getInstance, SettingsConstants::maximized.
Referenced by MainWindow::restoreWindow.
void QtPassSettings::setMaximized(const bool &maximized)
Save maximized state.
maximized Maximized state to save.
References getInstance, SettingsConstants::maximized.
Referenced by MainWindow::closeEvent.
QByteArray QtPassSettings::getDialogGeometry(const QString &key, const QByteArray &defaultValue=QVariant().toByteArray())
Get saved dialog geometry.
key Dialog identifier (e.g., "usersDialog"). defaultValue Byte array returned if not saved. Dialog geometry as QByteArray.
References SettingsConstants::dialogGeometry, getInstance.
Referenced by ConfigDialog::ConfigDialog, KeygenDialog::KeygenDialog.
void QtPassSettings::setDialogGeometry(const QString &key, const QByteArray &geometry)
Save dialog geometry.
key Dialog identifier. geometry Dialog geometry to save.
References SettingsConstants::dialogGeometry, getInstance.
Referenced by ConfigDialog::closeEvent, KeygenDialog::closeEvent, UsersDialog::closeEvent.
QPoint QtPassSettings::getDialogPos(const QString &key, const QPoint &defaultValue=QVariant().toPoint())
Get saved dialog position.
key Dialog identifier. defaultValue Point returned if not saved. Dialog position as QPoint.
References SettingsConstants::dialogPos, getInstance.
Referenced by KeygenDialog::KeygenDialog.
void QtPassSettings::setDialogPos(const QString &key, const QPoint &pos)
Save dialog position.
key Dialog identifier. pos Dialog position to save.
References SettingsConstants::dialogPos, getInstance.
Referenced by ConfigDialog::closeEvent, KeygenDialog::closeEvent, UsersDialog::closeEvent.
QSize QtPassSettings::getDialogSize(const QString &key, const QSize &defaultValue=QVariant().toSize())
Get saved dialog size.
key Dialog identifier. defaultValue Size returned if not saved. Dialog size as QSize.
References SettingsConstants::dialogSize, getInstance.
Referenced by KeygenDialog::KeygenDialog.
void QtPassSettings::setDialogSize(const QString &key, const QSize &size)
Save dialog size.
key Dialog identifier. size Dialog size to save.
References SettingsConstants::dialogSize, getInstance.
Referenced by ConfigDialog::closeEvent, KeygenDialog::closeEvent, UsersDialog::closeEvent.
bool QtPassSettings::isDialogMaximized(const QString &key, const bool &defaultValue=QVariant().toBool())
Get dialog maximized state.
key Dialog identifier. defaultValue Boolean returned if not saved. true if dialog is maximized.
References SettingsConstants::dialogMaximized, getInstance.
Referenced by ConfigDialog::ConfigDialog, KeygenDialog::KeygenDialog.
void QtPassSettings::setDialogMaximized(const QString &key, const bool &maximized)
Save dialog maximized state.
key Dialog identifier. maximized Maximized state to save.
References SettingsConstants::dialogMaximized, getInstance.
Referenced by ConfigDialog::closeEvent, KeygenDialog::closeEvent, UsersDialog::closeEvent.
bool QtPassSettings::isUsePass(const bool &defaultValue=QVariant().toBool())
Get whether to use pass (true) or GPG (false).
defaultValue Boolean returned if not saved (defaults to false). true if using pass, false if using GPG.
References getInstance, SettingsConstants::usePass.
Referenced by ConfigDialog::ConfigDialog, Util::configIsValid, getPass.
void QtPassSettings::setUsePass(const bool &usePass)
Save use pass setting.
usePass true to use pass, false for GPG.
References getInstance, SettingsConstants::usePass.
Referenced by MainWindow::config.
int QtPassSettings::getClipBoardTypeRaw(const Enums::clipBoardType &defaultValue=Enums::CLIPBOARD_NEVER)
Get clipboard type preference.
defaultValue Default value returned if not saved. Clipboard type as Enums::clipBoardType.
References SettingsConstants::clipBoardType, getInstance.
Referenced by ConfigDialog::ConfigDialog, getClipBoardType.
Enums::clipBoardType QtPassSettings::getClipBoardType(const Enums::clipBoardType &defaultValue=Enums::CLIPBOARD_NEVER)
Get clipboard type as enum.
defaultValue Default value returned if not saved. Clipboard type as Enums::clipBoardType.
References getClipBoardTypeRaw.
Referenced by QtPass::setClippedText.
void QtPassSettings::setClipBoardType(const int &clipBoardType)
Save clipboard type.
clipBoardType Clipboard type to save.
References SettingsConstants::clipBoardType, getInstance.
bool QtPassSettings::isUseSelection(const bool &defaultValue=QVariant().toBool())
Get whether to use selection (X11) for clipboard.
defaultValue Boolean returned if not saved. true if using selection.
References getInstance, SettingsConstants::useSelection.
Referenced by ConfigDialog::ConfigDialog, QtPass::copyTextToClipboard.
void QtPassSettings::setUseSelection(const bool &useSelection)
Save use selection setting.
useSelection true to use selection.
References getInstance, SettingsConstants::useSelection.
bool QtPassSettings::isUseAutoclear(const bool &defaultValue=QVariant().toBool())
Get whether to use autoclear for clipboard.
defaultValue Boolean returned if not saved. true if autoclear is enabled.
References getInstance, SettingsConstants::useAutoclear.
Referenced by ConfigDialog::ConfigDialog, QtPass::copyTextToClipboard.
void QtPassSettings::setUseAutoclear(const bool &useAutoclear)
Save use autoclear setting.
useAutoclear true to enable autoclear.
References getInstance, SettingsConstants::useAutoclear.
int QtPassSettings::getAutoclearSeconds(const int &defaultValue=QVariant().toInt())
Get autoclear delay in seconds.
defaultValue Integer returned if not saved. Seconds before clipboard is cleared.
References SettingsConstants::autoclearSeconds, getInstance.
Referenced by ConfigDialog::ConfigDialog, QtPass::init, QtPass::setClipboardTimer.
void QtPassSettings::setAutoclearSeconds(const int &autoClearSeconds)
Save autoclear seconds.
autoClearSeconds Seconds to wait before clearing.
References SettingsConstants::autoclearSeconds, getInstance.
Referenced by QtPass::init.
bool QtPassSettings::isUseAutoclearPanel(const bool &defaultValue=QVariant().toBool())
Get whether to use panel autoclear.
defaultValue Boolean returned if not saved. true if panel autoclear is enabled.
References getInstance, SettingsConstants::useAutoclearPanel.
Referenced by ConfigDialog::ConfigDialog, MainWindow::onGrepFinished, MainWindow::passOtpHandler, MainWindow::passShowHandler.
void QtPassSettings::setUseAutoclearPanel(const bool &useAutoclearPanel)
Save use autoclear panel setting.
useAutoclearPanel true to enable panel autoclear.
References getInstance, SettingsConstants::useAutoclearPanel.
int QtPassSettings::getAutoclearPanelSeconds(const int &defaultValue=QVariant().toInt())
Get panel autoclear delay in seconds.
defaultValue Integer returned if not saved. Seconds before panel is cleared.
References SettingsConstants::autoclearPanelSeconds, getInstance.
Referenced by MainWindow::config, ConfigDialog::ConfigDialog, QtPass::init, MainWindow::MainWindow.
void QtPassSettings::setAutoclearPanelSeconds(const int &autoClearPanelSeconds)
Save panel autoclear seconds.
autoClearPanelSeconds Seconds to wait before clearing panel.
References SettingsConstants::autoclearPanelSeconds, getInstance.
Referenced by QtPass::init.
bool QtPassSettings::isHidePassword(const bool &defaultValue=QVariant().toBool())
Get whether to hide password in UI.
defaultValue Boolean returned if not saved. true if password is hidden.
References getInstance, SettingsConstants::hidePassword.
Referenced by ConfigDialog::ConfigDialog.
void QtPassSettings::setHidePassword(const bool &hidePassword)
Save hide password setting.
hidePassword true to hide password.
References getInstance, SettingsConstants::hidePassword.
bool QtPassSettings::isHideContent(const bool &defaultValue=QVariant().toBool())
Get whether to hide content (password + username).
defaultValue Boolean returned if not saved. true if content is hidden.
References getInstance, SettingsConstants::hideContent.
Referenced by ConfigDialog::ConfigDialog, MainWindow::onGrepFinished, MainWindow::passShowHandler.
void QtPassSettings::setHideContent(const bool &hideContent)
Save hide content setting.
hideContent true to hide content.
References getInstance, SettingsConstants::hideContent.
bool QtPassSettings::isUseMonospace(const bool &defaultValue=QVariant().toBool())
Get whether to use monospace font.
defaultValue Boolean returned if not saved. true if using monospace font.
References getInstance, SettingsConstants::useMonospace.
Referenced by ConfigDialog::ConfigDialog, MainWindow::MainWindow.
void QtPassSettings::setUseMonospace(const bool &useMonospace)
Save use monospace setting.
useMonospace true to use monospace font.
References getInstance, SettingsConstants::useMonospace.
bool QtPassSettings::isDisplayAsIs(const bool &defaultValue=QVariant().toBool())
Get whether to display password as-is (no modification).
defaultValue Boolean returned if not saved. true if displaying as-is.
References SettingsConstants::displayAsIs, getInstance.
Referenced by ConfigDialog::ConfigDialog, MainWindow::passShowHandler.
void QtPassSettings::setDisplayAsIs(const bool &displayAsIs)
Save display as-is setting.
displayAsIs true to display unmodified.
References SettingsConstants::displayAsIs, getInstance.
bool QtPassSettings::isNoLineWrapping(const bool &defaultValue=QVariant().toBool())
Get whether to disable line wrapping.
defaultValue Boolean returned if not saved. true if line wrapping disabled.
References getInstance, SettingsConstants::noLineWrapping.
Referenced by ConfigDialog::ConfigDialog, MainWindow::MainWindow.
void QtPassSettings::setNoLineWrapping(const bool &noLineWrapping)
Save no line wrapping setting.
noLineWrapping true to disable wrapping.
References getInstance, SettingsConstants::noLineWrapping.
bool QtPassSettings::isAddGPGId(const bool &defaultValue=QVariant().toBool())
Get whether to auto-add GPG ID when receiving files.
defaultValue Boolean returned if not saved. true if auto-adding is enabled.
References SettingsConstants::addGPGId, getInstance.
Referenced by ConfigDialog::ConfigDialog, ImitatePass::Init.
void QtPassSettings::setAddGPGId(const bool &addGPGId)
Save add GPG ID setting.
addGPGId true to auto-add GPG IDs.
References SettingsConstants::addGPGId, getInstance.
QString QtPassSettings::getPassStore(const QString &defaultValue=QVariant().toString())
Get password store directory path.
defaultValue String returned if not saved. Path to password store.
References getInstance, SettingsConstants::passStore.
Referenced by MainWindow::config, ConfigDialog::ConfigDialog, Util::configIsValid, RealPass::Copy, ImitatePass::executeMoveGit, Pass::executeWrapper, Util::getDir, Pass::getGpgIdPath, ImitatePass::GitInit, ImitatePass::Grep, RealPass::Init, QtPass::init, ImitatePass::Insert, isUseGit, MainWindow::MainWindow, RealPass::Move, ImitatePass::reencryptSingleFile, ImitatePass::Remove, ImitatePass::Show, Pass::updateEnv, QtPass::~QtPass.
void QtPassSettings::setPassStore(const QString &passStore)
Save password store path.
passStore Path to password store.
References getInstance, SettingsConstants::passStore.
Referenced by QtPass::init.
QString QtPassSettings::getPassSigningKey(const QString &defaultValue=QVariant().toString())
Get GPG signing key for pass.
defaultValue String returned if not saved. GPG key ID.
References getInstance, SettingsConstants::passSigningKey.
Referenced by ImitatePass::Init, Pass::updateEnv, ImitatePass::verifyGpgIdFile.
void QtPassSettings::setPassSigningKey(const QString &passSigningKey)
Save GPG signing key.
passSigningKey Key ID to use for signing.
References getInstance, SettingsConstants::passSigningKey.
void QtPassSettings::initExecutables()
Initialize executable paths by auto-detecting them.
References Util::findBinaryInPath, getGitExecutable, getGpgExecutable, getPassExecutable, getPwgenExecutable, setGitExecutable, setGpgExecutable, setPassExecutable, setPwgenExecutable.
Referenced by QtPass::init.
QString QtPassSettings::getPassExecutable(const QString &defaultValue=QVariant().toString())
Get pass executable path.
defaultValue String returned if not saved. Path to pass executable.
References getInstance, SettingsConstants::passExecutable.
Referenced by MainWindow::config, ConfigDialog::ConfigDialog, Util::configIsValid, RealPass::GitPull_b, initExecutables.
void QtPassSettings::setPassExecutable(const QString &passExecutable)
Save pass executable path.
passExecutable Path to pass.
References getInstance, SettingsConstants::passExecutable.
Referenced by initExecutables, ConfigDialog::~ConfigDialog.
QString QtPassSettings::getGitExecutable(const QString &defaultValue=QVariant().toString())
Get git executable path.
defaultValue String returned if not saved. Path to git executable.
References getInstance, SettingsConstants::gitExecutable.
Referenced by ConfigDialog::ConfigDialog, ImitatePass::createBackupCommit, ImitatePass::executeGit, ImitatePass::GitPull_b, ImitatePass::Init, initExecutables, ImitatePass::reencryptSingleFile.
void QtPassSettings::setGitExecutable(const QString &gitExecutable)
Save git executable path.
gitExecutable Path to git.
References getInstance, SettingsConstants::gitExecutable.
Referenced by initExecutables, ConfigDialog::~ConfigDialog.
QString QtPassSettings::getGpgExecutable(const QString &defaultValue=QVariant().toString())
Get GPG executable path.
defaultValue String returned if not saved. Path to GPG executable.
References getInstance, SettingsConstants::gpgExecutable.
Referenced by ImitatePass::checkSigningKeys, ConfigDialog::ConfigDialog, Util::configIsValid, ImitatePass::executeGpg, Pass::GenerateGPGKeys, ImitatePass::getKeysFromFile, Pass::gpgSupportsEd25519, ImitatePass::Grep, initExecutables, Pass::listKeys, ImitatePass::reencryptSingleFile, ImitatePass::signGpgIdFile, ImitatePass::verifyGpgIdFile.
void QtPassSettings::setGpgExecutable(const QString &gpgExecutable)
Save GPG executable path.
gpgExecutable Path to GPG executable.
References getInstance, SettingsConstants::gpgExecutable.
Referenced by initExecutables, ConfigDialog::~ConfigDialog.
QString QtPassSettings::getPwgenExecutable(const QString &defaultValue=QVariant().toString())
Get pwgen executable path.
defaultValue String returned if not saved. Path to pwgen executable.
References getInstance, SettingsConstants::pwgenExecutable.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword, QtPass::init, initExecutables.
void QtPassSettings::setPwgenExecutable(const QString &pwgenExecutable)
Save pwgen executable path.
pwgenExecutable Path to pwgen.
References getInstance, SettingsConstants::pwgenExecutable.
Referenced by initExecutables.
QString QtPassSettings::getGpgHome(const QString &defaultValue=QVariant().toString())
Get GPG home directory.
defaultValue String returned if not saved. Path to the GPG home directory.
References getInstance, SettingsConstants::gpgHome.
Referenced by Pass::init.
bool QtPassSettings::isUseWebDav(const bool &defaultValue=QVariant().toBool())
Check whether WebDAV integration is enabled.
defaultValue Value returned if not saved. True if WebDAV is enabled.
References getInstance, SettingsConstants::useWebDav.
Referenced by ImitatePass::Init, QtPass::init, ImitatePass::Insert, ImitatePass::reencryptSingleFile, QtPass::~QtPass.
void QtPassSettings::setUseWebDav(const bool &useWebDav)
Save WebDAV integration flag.
useWebDav Whether to enable WebDAV.
References getInstance, SettingsConstants::useWebDav.
QString QtPassSettings::getWebDavUrl(const QString &defaultValue=QVariant().toString())
Get WebDAV URL.
defaultValue String returned if not saved. WebDAV URL.
References getInstance, SettingsConstants::webDavUrl.
void QtPassSettings::setWebDavUrl(const QString &webDavUrl)
Save WebDAV URL.
webDavUrl WebDAV URL.
References getInstance, SettingsConstants::webDavUrl.
QString QtPassSettings::getWebDavUser(const QString &defaultValue=QVariant().toString())
Get WebDAV username.
defaultValue String returned if not saved. WebDAV username.
References getInstance, SettingsConstants::webDavUser.
void QtPassSettings::setWebDavUser(const QString &webDavUser)
Save WebDAV username.
webDavUser WebDAV username.
References getInstance, SettingsConstants::webDavUser.
QString QtPassSettings::getWebDavPassword(const QString &defaultValue=QVariant().toString())
Get WebDAV password.
defaultValue String returned if not saved. WebDAV password.
References getInstance, SettingsConstants::webDavPassword.
void QtPassSettings::setWebDavPassword(const QString &webDavPassword)
Save WebDAV password.
webDavPassword WebDAV password.
References getInstance, SettingsConstants::webDavPassword.
QString QtPassSettings::getProfile(const QString &defaultValue=QVariant().toString())
Get active profile name.
defaultValue String returned if not saved. Active profile name.
References getInstance, SettingsConstants::profile.
Referenced by ConfigDialog::ConfigDialog.
void QtPassSettings::setProfile(const QString &profile)
Save active profile name.
profile Profile name.
References getInstance, SettingsConstants::profile.
bool QtPassSettings::isUseGit(const bool &defaultValue=QVariant().toBool())
Check whether Git integration is enabled.
defaultValue Value returned if not saved. True if Git integration is enabled.
References getInstance, getPassStore, SettingsConstants::useGit.
Referenced by ConfigDialog::ConfigDialog, ImitatePass::Copy, ImitatePass::createBackupCommit, ImitatePass::GitPush, ImitatePass::Init, ImitatePass::Insert, ImitatePass::Move, MainWindow::onPush, ImitatePass::reencryptSingleFile, ImitatePass::Remove.
void QtPassSettings::setUseGit(const bool &useGit)
Save Git integration flag.
useGit Whether to enable Git integration.
References getInstance, SettingsConstants::useGit.
bool QtPassSettings::isUseGrepSearch(const bool &defaultValue=false)
Check whether content search (pass grep) is enabled.
defaultValue Value returned if not saved (defaults to false). True if grep search is enabled.
References getInstance, SettingsConstants::useGrepSearch.
Referenced by ConfigDialog::ConfigDialog.
void QtPassSettings::setUseGrepSearch(const bool &useGrepSearch)
Save content search flag.
useGrepSearch Whether to enable grep search.
References getInstance, SettingsConstants::useGrepSearch.
bool QtPassSettings::isUseOtp(const bool &defaultValue=QVariant().toBool())
Check whether OTP support is enabled.
defaultValue Value returned if not saved. True if OTP support is enabled.
References getInstance, SettingsConstants::useOtp.
Referenced by ConfigDialog::ConfigDialog.
void QtPassSettings::setUseOtp(const bool &useOtp)
Save OTP support flag.
useOtp Whether to enable OTP support.
References getInstance, SettingsConstants::useOtp.
bool QtPassSettings::isUseQrencode(const bool &defaultValue=QVariant().toBool())
Check whether qrencode support is enabled.
defaultValue Value returned if not saved. True if qrencode support is enabled.
References getInstance, SettingsConstants::useQrencode.
Referenced by ConfigDialog::ConfigDialog.
void QtPassSettings::setUseQrencode(const bool &useQrencode)
Save qrencode support flag.
useQrencode Whether to enable qrencode support.
References getInstance, SettingsConstants::useQrencode.
QString QtPassSettings::getQrencodeExecutable(const QString &defaultValue=QVariant().toString())
Get qrencode executable path.
defaultValue String returned if not saved. Path to qrencode executable.
References getInstance, SettingsConstants::qrencodeExecutable.
Referenced by QtPass::showTextAsQRCode.
void QtPassSettings::setQrencodeExecutable(const QString &qrencodeExecutable)
Save qrencode executable path.
qrencodeExecutable Path to qrencode executable.
References getInstance, SettingsConstants::qrencodeExecutable.
bool QtPassSettings::isUsePwgen(const bool &defaultValue=QVariant().toBool())
Check whether pwgen support is enabled.
defaultValue Value returned if not saved. True if pwgen support is enabled.
References getInstance, SettingsConstants::usePwgen.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword, PasswordDialog::PasswordDialog.
void QtPassSettings::setUsePwgen(const bool &usePwgen)
Save pwgen support flag.
usePwgen Whether to enable pwgen support.
References getInstance, SettingsConstants::usePwgen.
Referenced by QtPass::init.
bool QtPassSettings::isAvoidCapitals(const bool &defaultValue=QVariant().toBool())
Check whether uppercase characters should be avoided.
defaultValue Value returned if not saved. True if uppercase characters are avoided.
References SettingsConstants::avoidCapitals, getInstance.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword.
void QtPassSettings::setAvoidCapitals(const bool &avoidCapitals)
Save uppercase avoidance flag.
avoidCapitals Whether uppercase characters should be avoided.
References SettingsConstants::avoidCapitals, getInstance.
bool QtPassSettings::isAvoidNumbers(const bool &defaultValue=QVariant().toBool())
Check whether numeric characters should be avoided.
defaultValue Value returned if not saved. True if numeric characters are avoided.
References SettingsConstants::avoidNumbers, getInstance.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword.
void QtPassSettings::setAvoidNumbers(const bool &avoidNumbers)
Save numeric avoidance flag.
avoidNumbers Whether numeric characters should be avoided.
References SettingsConstants::avoidNumbers, getInstance.
bool QtPassSettings::isLessRandom(const bool &defaultValue=QVariant().toBool())
Check whether less random password generation is enabled.
defaultValue Value returned if not saved. True if less random generation is enabled.
References getInstance, SettingsConstants::lessRandom.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword.
void QtPassSettings::setLessRandom(const bool &lessRandom)
Save less-random generation flag.
lessRandom Whether less-random generation is enabled.
References getInstance, SettingsConstants::lessRandom.
bool QtPassSettings::isUseSymbols(const bool &defaultValue=QVariant().toBool())
Check whether symbol characters are enabled.
defaultValue Value returned if not saved. True if symbol characters are enabled.
References getInstance, SettingsConstants::useSymbols.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword.
void QtPassSettings::setUseSymbols(const bool &useSymbols)
Save symbol usage flag.
useSymbols Whether symbol characters are enabled.
References getInstance, SettingsConstants::useSymbols.
PasswordConfiguration QtPassSettings::getPasswordConfiguration()
Get complete password generation configuration.
Password generation configuration.
References PasswordConfiguration::Characters, PasswordConfiguration::CUSTOM, getInstance, PasswordConfiguration::length, SettingsConstants::passwordChars, SettingsConstants::passwordCharsSelection, SettingsConstants::passwordLength, PasswordConfiguration::selected.
Referenced by ConfigDialog::ConfigDialog, Pass::generatePassword, PasswordDialog::PasswordDialog, Pass::updateEnv.
void QtPassSettings::setPasswordConfiguration(const PasswordConfiguration &config)
Save complete password generation configuration.
config Password generation configuration.
References PasswordConfiguration::Characters, PasswordConfiguration::CUSTOM, getInstance, PasswordConfiguration::length, SettingsConstants::passwordChars, SettingsConstants::passwordCharsSelection, SettingsConstants::passwordLength, PasswordConfiguration::selected.
void QtPassSettings::setPasswordLength(const int &passwordLength)
Save password length setting.
passwordLength Password length.
References getInstance, SettingsConstants::passwordLength.
void QtPassSettings::setPasswordCharsSelection(const int &passwordCharsSelection)
Save password character selection mode.
passwordCharsSelection Password character selection mode.
References getInstance, SettingsConstants::passwordCharsSelection.
void QtPassSettings::setPasswordChars(const QString &passwordChars)
Save custom password characters.
passwordChars Custom characters used for password generation.
References getInstance, SettingsConstants::passwordChars.
bool QtPassSettings::isUseTrayIcon(const bool &defaultValue=QVariant().toBool())
Check whether tray icon support is enabled.
defaultValue Value returned if not saved. True if tray icon support is enabled.
References getInstance, SettingsConstants::useTrayIcon.
Referenced by MainWindow::config, ConfigDialog::ConfigDialog, MainWindow::restoreWindow.
void QtPassSettings::setUseTrayIcon(const bool &useTrayIcon)
Save tray icon support flag.
useTrayIcon Whether tray icon support is enabled.
References getInstance, SettingsConstants::useTrayIcon.
bool QtPassSettings::isHideOnClose(const bool &defaultValue=QVariant().toBool())
Check whether closing the window hides the application.
defaultValue Value returned if not saved. True if close action hides the application.
References getInstance, SettingsConstants::hideOnClose.
Referenced by MainWindow::closeEvent, ConfigDialog::ConfigDialog.
void QtPassSettings::setHideOnClose(const bool &hideOnClose)
Save hide-on-close flag.
hideOnClose Whether close action should hide the application.
References getInstance, SettingsConstants::hideOnClose.
bool QtPassSettings::isStartMinimized(const bool &defaultValue=QVariant().toBool())
Check whether application should start minimized.
defaultValue Value returned if not saved. True if application should start minimized.
References getInstance, SettingsConstants::startMinimized.
Referenced by ConfigDialog::ConfigDialog, MainWindow::restoreWindow.
void QtPassSettings::setStartMinimized(const bool &startMinimized)
Save start-minimized flag.
startMinimized Whether application should start minimized.
References getInstance, SettingsConstants::startMinimized.
bool QtPassSettings::isAlwaysOnTop(const bool &defaultValue=QVariant().toBool())
Check whether main window should stay always on top.
defaultValue Value returned if not saved. True if always-on-top is enabled.
References SettingsConstants::alwaysOnTop, getInstance.
Referenced by ConfigDialog::ConfigDialog, MainWindow::restoreWindow.
void QtPassSettings::setAlwaysOnTop(const bool &alwaysOnTop)
Save always-on-top flag.
alwaysOnTop Whether always-on-top should be enabled.
References SettingsConstants::alwaysOnTop, getInstance.
bool QtPassSettings::isAutoPull(const bool &defaultValue=QVariant().toBool())
Check whether automatic pull is enabled.
defaultValue Value returned if not saved. True if automatic pull is enabled.
References SettingsConstants::autoPull, getInstance.
Referenced by ConfigDialog::ConfigDialog, ImitatePass::reencryptPath.
void QtPassSettings::setAutoPull(const bool &autoPull)
Save automatic pull flag.
autoPull Whether automatic pull should be enabled.
References SettingsConstants::autoPull, getInstance.
bool QtPassSettings::isAutoPush(const bool &defaultValue=QVariant().toBool())
Check whether automatic push is enabled.
defaultValue Value returned if not saved. True if automatic push is enabled.
References SettingsConstants::autoPush, getInstance.
Referenced by ConfigDialog::ConfigDialog, ImitatePass::reencryptPath.
void QtPassSettings::setAutoPush(const bool &autoPush)
Save automatic push flag.
autoPush Whether automatic push should be enabled.
References SettingsConstants::autoPush, getInstance.
QString QtPassSettings::getPassTemplate(const QString &defaultValue=QVariant().toString())
Get pass entry template.
defaultValue String returned if not saved. Pass template.
References getInstance, SettingsConstants::passTemplate.
Referenced by ConfigDialog::ConfigDialog, QtPass::init, MainWindow::passShowHandler, PasswordDialog::PasswordDialog.
void QtPassSettings::setPassTemplate(const QString &passTemplate)
Save pass entry template.
passTemplate Pass template.
References getInstance, SettingsConstants::passTemplate.
Referenced by QtPass::init.
bool QtPassSettings::isUseTemplate(const bool &defaultValue=QVariant().toBool())
Check whether template usage is enabled.
defaultValue Value returned if not saved. True if template usage is enabled.
References getInstance, SettingsConstants::useTemplate.
Referenced by ConfigDialog::ConfigDialog, MainWindow::passShowHandler, PasswordDialog::PasswordDialog.
void QtPassSettings::setUseTemplate(const bool &useTemplate)
Save template usage flag.
useTemplate Whether template usage should be enabled.
References getInstance, SettingsConstants::useTemplate.
bool QtPassSettings::isTemplateAllFields(const bool &defaultValue=QVariant().toBool())
Check whether template applies to all fields.
defaultValue Value returned if not saved. True if template applies to all fields.
References getInstance, SettingsConstants::templateAllFields.
Referenced by ConfigDialog::ConfigDialog, MainWindow::passShowHandler, PasswordDialog::PasswordDialog.
void QtPassSettings::setTemplateAllFields(const bool &templateAllFields)
Save template-all-fields flag.
templateAllFields Whether template should apply to all fields.
References getInstance, SettingsConstants::templateAllFields.
QHash< QString, QHash< QString, QString > > QtPassSettings::getProfiles()
Get all configured profiles.
Profile map keyed by profile name.
References getInstance, SettingsConstants::profile.
Referenced by ConfigDialog::ConfigDialog.
void QtPassSettings::setProfiles(const QHash< QString, QHash< QString, QString > > &profiles)
Save all configured profiles.
profiles Profile map keyed by profile name.
References getInstance, SettingsConstants::profile.
Pass * QtPassSettings::getPass()
Get currently active pass backend instance.
Pointer to pass backend.
References getImitatePass, getRealPass, isUsePass.
Referenced by UsersDialog::accept, MainWindow::config, MainWindow::MainWindow, MainWindow::on_treeView_clicked, MainWindow::onPush, PasswordDialog::PasswordDialog, PasswordDialog::PasswordDialog.
RealPass * QtPassSettings::getRealPass()
Get real pass backend instance.
Pointer to real pass backend.
Referenced by getPass.
ImitatePass * QtPassSettings::getImitatePass()
Get imitate pass backend instance.
Pointer to imitate pass backend.
Referenced by getPass.