FileContent
QString FileContent::password
NamedValues FileContent::namedValues
QString FileContent::remainingData
QString FileContent::remainingDataDisplay
FileContent FileContent::parse(const QString &fileContent, const QStringList &templateFields, bool allFields)
parse parses the given fileContent in a FileContent object. The password is accessible through getPassword. The named value pairs (name: value) are parsed and depeding on the templateFields and allFields parameters accessible through getNamedValues, getRemainingData or getRemainingDataForDisplay.
Parses password file content into structured data. fileContent the file content to parse. templateFields the fields in the template. Fields in the template will always be in getNamedValues() at the beginning of the list in the same order. allFields whether all fields should be considered as named values. If set to false only templateFields are returned in getNamedValues(). fileContent Raw file content templateFields Fields defined in the template allFields Whether to include all name:value pairs Parsed FileContent object
References AS_CONST.
Referenced by MainWindow::passShowHandler, PasswordDialog::setPassword.
QString FileContent::getPassword() const
Gets the password from the parsed file.
the password from the parsed file. The password string
Referenced by MainWindow::passShowHandler, PasswordDialog::setPassword.
NamedValues FileContent::getNamedValues() const
Gets named value pairs from the parsed file.
the named values in the file in the order of appearence, with template values first. NamedValues list with name:value pairs
Referenced by MainWindow::passShowHandler, PasswordDialog::setPassword.
QString FileContent::getRemainingData() const
Gets remaining data not in named values.
the data that is not the password and not in getNamedValues. Remaining data as string
Referenced by PasswordDialog::setPassword.
QString FileContent::getRemainingDataForDisplay() const
Gets remaining data for display (excludes hidden fields like OTP).
@like getRemainingData but without data that should not be displayed (like a TOTP secret). Remaining data suitable for display
Referenced by MainWindow::passShowHandler.
FileContent::FileContent(QString password, NamedValues namedValues, QString remainingData, QString remainingDataDisplay)
Constructs a FileContent with all parsed data.
password The password namedValues Named value pairs remainingData Remaining data not in named values remainingDataDisplay Remaining data for display