simpleTransaction
int simpleTransaction::transactionDepth
Enums::PROCESS simpleTransaction::lastInTransaction
std::queue<std::pair<Enums::PROCESS, Enums::PROCESS> > simpleTransaction::transactionQueue
simpleTransaction::simpleTransaction()
References INVALID.
Referenced by ImitatePass::transactionHelper::transactionHelper.
void simpleTransaction::transactionStart()
transactionStart this function is used to mark start of the sequence of processes that shall be treated as one operation.
Marks the start of a sequence of processes that shall be treated as one operation.
References dbg.
void simpleTransaction::transactionAdd(Enums::PROCESS)
transactionAdd If called after call to transactionStart() and before transactionEnd(), this method marks given process as next step in transaction. Otherwise it marks given process as the only step in transaction(it's value is treated as transaction result).
If called after transactionStart() and before transactionEnd(), this marks the given process as the next step in the transaction. Otherwise it marks the process as the only step in the transaction. id process that shall be treated as part of transaction id Process that shall be treated as part of the transaction
References dbg.
Referenced by ImitatePass::executeWrapper.
void simpleTransaction::transactionEnd(Enums::PROCESS)
transactionEnd marks end of transaction
Marks the end of the current transaction. pid value that will be used as a result of transaction pid Value that will be used as the result of the transaction
References dbg, INVALID.
Enums::PROCESS simpleTransaction::transactionIsOver(Enums::PROCESS)
transactionIsOver checks wheather currently finished process is last in current transaction
Checks whether the currently finished process is last in current transaction. result of transaction as set by transactionAdd or transactionEnd if the transaction is over or PROCESS::INVALID if it's not yet over id The process id to check Result of transaction as set by transactionAdd or transactionEnd, or PROCESS::INVALID if the transaction is not yet over
References dbg, INVALID.
Referenced by ImitatePass::finished.