MainWindow
QtPass* MainWindow::m_qtPass
QScopedPointer<Ui::MainWindow> MainWindow::ui
bool MainWindow::m_grepMode
bool MainWindow::m_grepBusy
bool MainWindow::m_grepCancelled
QFileSystemModel MainWindow::model
StoreModel MainWindow::proxyModel
QScopedPointer<QItemSelectionModel> MainWindow::selectionModel
QTimer MainWindow::clearPanelTimer
QTimer MainWindow::searchTimer
QDialog* MainWindow::keygen
QString MainWindow::currentDir
TrayIcon* MainWindow::tray
MainWindow::MainWindow(const QString &searchText=QString(), QWidget *parent=nullptr)
MainWindow::MainWindow handles all of the main functionality and also the main window.
searchText for searching from cli parent pointer
References deselect, DeselectableTreeView::emptyClicked, Util::findPasswordStore, QtPassSettings::getAutoclearPanelSeconds, QtPassSettings::getPass, QtPassSettings::getPassStore, QtPassSettings::isNoLineWrapping, QtPassSettings::isUseMonospace, MainWindow, MS_PER_SECOND, setUiElementsEnabled.
Referenced by MainWindow.
MainWindow::~MainWindow() override
void MainWindow::restoreWindow()
Restore window geometry and state from saved settings.
References QtPassSettings::getGeometry, QtPassSettings::getPos, QtPassSettings::getSavestate, QtPassSettings::getSize, QtPassSettings::isAlwaysOnTop, QtPassSettings::isMaximized, QtPassSettings::isStartMinimized, QtPassSettings::isUseTrayIcon.
void MainWindow::generateKeyPair(const QString &batch, QDialog *dialog)
Open the GPG key generation dialog.
MainWindow::generateKeyPair internal gpg keypair generator . . batch GPG batch parameter string. dialog Parent dialog to return to after generation. batch keygenWindow
References generateGPGKeyPair.
void MainWindow::userDialog(const QString &dir="")
Open the user/recipient management dialog.
MainWindow::userDialog see MainWindow::onUsers(). dir Directory for which to manage recipients. dir folder to edit users for.
void MainWindow::config()
Open the configuration dialog.
References config, Util::configIsValid, deselect, QtPassSettings::getAutoclearPanelSeconds, QtPassSettings::getPass, QtPassSettings::getPassExecutable, QtPassSettings::getPassStore, QtPassSettings::isUseTrayIcon, MS_PER_SECOND, QtPassSettings::setUsePass.
Referenced by config.
void MainWindow::setUiElementsEnabled(bool state)
Enable or disable the main UI elements.
MainWindow::setUiElementsEnabled enable or disable the relevant UI elements. state true to enable, false to disable. state
Referenced by endReencryptPath, executeWrapperStarted, MainWindow, onGrepFinished, passOtpHandler, passShowHandler, startReencryptPath.
void MainWindow::flashText(const QString &text, const bool isError, const bool isHtml=false)
Display a transient message in the text panel.
text Message text to display. isError true to style the message as an error. isHtml true if text contains HTML markup.
Referenced by passOtpHandler.
QModelIndex MainWindow::getCurrentTreeViewIndex()
Return the currently selected index in the tree view.
Current QModelIndex.
QDialog * MainWindow::getKeygenDialog()
Return the active key generation dialog, if any.
Pointer to the keygen QDialog, or nullptr.
void MainWindow::cleanKeygenDialog()
Destroy and clear the key generation dialog.
void MainWindow::closeEvent(QCloseEvent *event) override
MainWindow::closeEvent hide or quit.
event
References QtPassSettings::isHideOnClose, QtPassSettings::setGeometry, QtPassSettings::setMaximized, QtPassSettings::setPos, QtPassSettings::setSavestate, QtPassSettings::setSize.
void MainWindow::keyPressEvent(QKeyEvent *event) override
MainWindow::keyPressEvent did anyone press return, enter or escape?
event
References on_treeView_clicked.
void MainWindow::changeEvent(QEvent *event) override
MainWindow::changeEvent sets focus to the search box.
event
bool MainWindow::eventFilter(QObject *obj, QEvent *event) override
MainWindow::eventFilter filter out some events and focus the treeview.
obj event
void MainWindow::passShowHandlerFinished(const QString &output)
Referenced by passShowHandler.
void MainWindow::passGitInitNeeded()
void MainWindow::generateGPGKeyPair(const QString &batch)
Referenced by generateKeyPair.
void MainWindow::deselect()
Clear the current tree view selection.
MainWindow::deselect clear the selection, password and copy buffer.
Referenced by config, MainWindow.
void MainWindow::messageAvailable(const QString &message)
Handle an incoming inter-process message (single-instance mode).
MainWindow::messageAvailable we have some text/message/search to do. message Message string received from another instance. message
Referenced by main.
void MainWindow::critical(const QString &title, const QString &msg)
Display a critical error dialog.
MainWindow::critical critical message popup wrapper. title Dialog title. msg Error message body. title msg
void MainWindow::executeWrapperStarted()
Slot called when an external process wrapper has started.
References setUiElementsEnabled.
void MainWindow::showStatusMessage(const QString &msg, int timeout=2000)
Show a message in the status bar for the given duration.
Displays message in status bar. msg Message to display. timeout Duration in milliseconds (default 2000). msg text to be displayed timeout time for which msg shall be visible
Referenced by passOtpHandler.
void MainWindow::passShowHandler(const QString &output)
Handle output from the pass show command.
output Decrypted password file content.
References FileContent::getNamedValues, QtPassSettings::getPassTemplate, FileContent::getPassword, FileContent::getRemainingDataForDisplay, QtPassSettings::isDisplayAsIs, QtPassSettings::isHideContent, QtPassSettings::isTemplateAllFields, QtPassSettings::isUseAutoclearPanel, QtPassSettings::isUseTemplate, NamedValue::name, FileContent::parse, passShowHandlerFinished, setUiElementsEnabled, NamedValue::value.
void MainWindow::passOtpHandler(const QString &output)
Handle output from the pass OTP command.
output OTP output string.
References flashText, QtPassSettings::isUseAutoclearPanel, setUiElementsEnabled, showStatusMessage.
void MainWindow::onGrepFinished(const QList< QPair< QString, QStringList > > &results)
Handle results from a completed grep search.
Display grep results in grepResultsList. results List of file/match pairs from the grep operation.
References QtPassSettings::isHideContent, QtPassSettings::isUseAutoclearPanel, setUiElementsEnabled.
void MainWindow::onPush()
Trigger a git push operation.
MainWindow::onPush do a git push.
References QtPassSettings::getPass, QtPassSettings::isUseGit.
void MainWindow::on_treeView_clicked(const QModelIndex &index)
Handle a click on an item in the tree view.
MainWindow::on_treeView_clicked read the selected password file. index The model index that was clicked. index
References Util::getDir, QtPassSettings::getPass.
Referenced by keyPressEvent.
void MainWindow::startReencryptPath()
Begin a re-encryption pass on the current path.
MainWindow::startReencryptPath disable ui elements and treeview.
References setUiElementsEnabled.
void MainWindow::endReencryptPath()
Finish a re-encryption pass on the current path.
MainWindow::endReencryptPath re-enable ui elements.
References setUiElementsEnabled.
void MainWindow::on_grepButton_toggled(bool checked)
Toggle grep (content search) mode.
void MainWindow::on_grepResultsList_itemClicked(QTreeWidgetItem *item, int column)
Navigate to the password entry when a grep result is clicked.
void MainWindow::addPassword()
MainWindow::addPassword add a new password by showing a number of dialogs.
void MainWindow::addFolder()
MainWindow::addFolder add a new folder to store passwords in.
void MainWindow::onEdit()
MainWindow::onEdit try and edit (selected) password.
void MainWindow::onDelete()
MainWindow::onDelete remove password, if you are sure.
void MainWindow::onOtp()
MainWindow::onOTP try and generate (selected) OTP code.
void MainWindow::onUpdate(bool block=false)
MainWindow::onUpdate do a git pull.
void MainWindow::onUsers()
MainWindow::onUsers edit users for the current folder, gets lists and opens UserDialog.
void MainWindow::onConfig()
MainWindow::on_configButton_clicked run Mainwindow::config.
void MainWindow::on_treeView_doubleClicked(const QModelIndex &index)
MainWindow::on_treeView_doubleClicked when doubleclicked on TreeViewItem, open the edit Window.
index
void MainWindow::clearPanel(bool notify=true)
MainWindow::clearPanel hide the information from shoulder surfers.
void MainWindow::on_lineEdit_textChanged(const QString &arg1)
Executes when the string in the search box changes, collapses the TreeView.
arg1
void MainWindow::on_lineEdit_returnPressed()
MainWindow::on_lineEdit_returnPressed get searching.
Select the first possible file in the tree
void MainWindow::on_profileBox_currentTextChanged(const QString &)
MainWindow::on_profileBox_currentIndexChanged make sure we show the correct "profile".
name Handles changes to the selected profile in the profile combo box. Ignores the event during a fresh start or when the selected profile matches the current profile. Otherwise, it clears the password field, updates the active profile and related settings, refreshes the environment, and resets the tree view and action states to reflect the newly selected profile. name - The newly selected profile name. void - This function does not return a value.
void MainWindow::showContextMenu(const QPoint &pos)
MainWindow::showContextMenu show us the (file or folder) context menu.
pos
void MainWindow::showBrowserContextMenu(const QPoint &pos)
MainWindow::showBrowserContextMenu show us the context menu in password window.
pos
void MainWindow::openFolder()
MainWindow::openFolder open the folder in the default file manager.
void MainWindow::renameFolder()
MainWindow::renameFolder rename an existing folder.
void MainWindow::editPassword(const QString &)
MainWindow::editPassword read password and open edit window via MainWindow::onEdit().
void MainWindow::renamePassword()
MainWindow::renamePassword rename an existing password.
void MainWindow::focusInput()
MainWindow::focusInput selects any text (if applicable) in the search box and sets focus to it. Allows for easy searching, called at application start and when receiving empty message in MainWindow::messageAvailable when compiled with SINGLE_APP=1 (default).
void MainWindow::copyPasswordFromTreeview()
void MainWindow::passwordFromFileToClipboard(const QString &text)
void MainWindow::onTimeoutSearch()
MainWindow::onTimeoutSearch Fired when search is finished or too much time from two keypresses is elapsed.
void MainWindow::initToolBarButtons()
MainWindow::initToolBarButtons init main ToolBar and connect actions.
void MainWindow::initStatusBar()
MainWindow::initStatusBar init statusBar with default message and logo.
void MainWindow::updateText()
void MainWindow::selectFirstFile()
MainWindow::selectFirstFile select the first possible file in the tree.
QModelIndex MainWindow::firstFile(QModelIndex parentIndex)
MainWindow::firstFile return location of first possible file.
parentIndex QModelIndex
QString MainWindow::getFile(const QModelIndex &, bool)
MainWindow::getFile get the selected file path.
index forPass returns relative path without '.gpg' extension path
void MainWindow::setPassword(const QString &, bool isNew=true)
MainWindow::setPassword open passworddialog.
file which pgp file isNew insert (not update)
void MainWindow::updateProfileBox()
MainWindow::updateProfileBox update the list of profiles, optionally select a more appropriate one to view too.
void MainWindow::initTrayIcon()
MainWindow::initTrayIcon show a nice tray icon on systems that support it.
void MainWindow::destroyTrayIcon()
MainWindow::destroyTrayIcon remove that pesky tray icon.
void MainWindow::clearTemplateWidgets()
MainWindow::clearTemplateWidgets empty the template widget fields in the UI.
void MainWindow::reencryptPath(const QString &dir)
MainWindow::reencryptPath re-encrypt all passwords in a directory.
dir Directory path to re-encrypt
void MainWindow::addToGridLayout(int position, const QString &field, const QString &value)
MainWindow::addToGridLayout add a field to the template grid.
position field value
void MainWindow::applyTextBrowserSettings()
MainWindow::config pops up the configuration screen and handles all inter-window communication.
void MainWindow::applyWindowFlagsSettings()
void MainWindow::updateGitButtonVisibility()
void MainWindow::updateOtpButtonVisibility()
void MainWindow::updateGrepButtonVisibility()
void MainWindow::enableGitButtons(const bool &)