Util
QProcessEnvironment Util::_env
bool Util::_envInitialised
QString Util::findBinaryInPath(const QString &binary)
Locate an executable by searching the process PATH and (on Windows) falling back to WSL.
binary Executable name or relative path to locate (e.g., "gpg" or "pass"). QString Absolute path to the executable if found, empty QString otherwise.
References dbg, Executor::executeBlocking.
Referenced by QtPassSettings::initExecutables.
QString Util::findPasswordStore()
Locate the password store directory.
Resolves the path to the password store directory. QString Path to the password store, always ends with native directory separator. Initializes the environment, checks for the PASSWORD_STORE_DIR variable, and falls back to a platform-specific default location under the user's home directory. QString - Normalized path to the password store folder.
References normalizeFolderPath.
Referenced by QtPass::init, MainWindow::MainWindow.
QString Util::normalizeFolderPath(const QString &path)
Ensure a folder path always ends with the native directory separator.
path The folder path to normalize. QString Path with trailing separator added if missing.
Referenced by findPasswordStore.
bool Util::configIsValid()
Verify that the required configuration is complete.
bool true if the password store's .gpg-id exists AND the configured executable (pass or gpg, depending on settings) exists or is a WSL wrapper; false otherwise.
References Executor::executeBlocking, QtPassSettings::getGpgExecutable, QtPassSettings::getPassExecutable, QtPassSettings::getPassStore, QtPassSettings::isUsePass.
Referenced by MainWindow::config, ConfigDialog::ConfigDialog, QtPass::init, ConfigDialog::wizard.
QString Util::getDir(const QModelIndex &index, bool forPass, const QFileSystemModel &model, const StoreModel &storeModel)
Get the selected folder path, either relative to the configured pass store or absolute.
index Model index selecting the file or folder. forPass If true, return the path relative to the pass store; otherwise return an absolute path. model Filesystem model used to resolve the index. storeModel StoreModel used to map view indexes to the filesystem model. QString Folder path that always ends with the native directory separator. Returns an empty string when index is invalid and forPass is true; otherwise returns the pass store root.
References QtPassSettings::getPassStore.
Referenced by MainWindow::on_treeView_clicked.
const QRegularExpression & Util::endsWithGpg()
Returns a regex to match .gpg file extensions.
Reference to static regex
Referenced by RealPass::Copy, StoreModel::data, ImitatePass::executeMoveGit, ImitatePass::gitAddGpgId, ImitatePass::Insert, RealPass::Move, ImitatePass::reencryptSingleFile, ImitatePass::Remove, StoreModel::showThis.
const QRegularExpression & Util::protocolRegex()
Returns a regex to match URL protocols.
Returns a regex matching common remote/network protocol schemes. Reference to static regex Matches http://, https://, ftp://, ftps://, ssh://, sftp://, webdav://, webdavs:// Note: Local file URLs (file:///) are intentionally excluded by design, as they represent local paths rather than network protocols. If this behavior needs to change, update both this function and the corresponding test. QRegularExpression reference
const QRegularExpression & Util::newLinesRegex()
Returns a regex to match newline characters.
Reference to static regex
Referenced by ImitatePass::getKeysFromFile, parseGpgColonOutput.
bool Util::isValidKeyId(const QString &keyId)
Check if a string looks like a valid GPG key ID. Accepts:
Key IDs: 8-40 hex characters (0-9, A-F, a-f), optional 0x prefix Emails: any string containing @ (e.g., user@domain.org, user@domain.org) Special prefixes: leading @, /, #, or & (any content after prefix) keyId The string to validate. true if the key ID format is valid, false otherwise.
Referenced by Pass::getRecipientList.
void Util::initialiseEnvironment()