ConfigDialog
QScopedPointer<Ui::ConfigDialog> ConfigDialog::ui
MainWindow* ConfigDialog::mainWindow
ConfigDialog::ConfigDialog(MainWindow *parent)
ConfigDialog::ConfigDialog this sets up the configuration screen.
parent
References ConfigDialog, Util::configIsValid, QtPassSettings::getAutoclearPanelSeconds, QtPassSettings::getAutoclearSeconds, QtPassSettings::getClipBoardTypeRaw, QtPassSettings::getDialogGeometry, QtPassSettings::getGitExecutable, QtPassSettings::getGpgExecutable, QtPassSettings::getPassExecutable, QtPassSettings::getPassStore, QtPassSettings::getPassTemplate, QtPassSettings::getPasswordConfiguration, QtPassSettings::getProfile, QtPassSettings::getProfiles, QtPassSettings::getPwgenExecutable, QtPassSettings::isAddGPGId, QtPassSettings::isAlwaysOnTop, QtPassSettings::isAutoPull, QtPassSettings::isAutoPush, QtPassSettings::isAvoidCapitals, QtPassSettings::isAvoidNumbers, QtPassSettings::isDialogMaximized, QtPassSettings::isDisplayAsIs, QtPassSettings::isHideContent, QtPassSettings::isHideOnClose, QtPassSettings::isHidePassword, QtPassSettings::isLessRandom, QtPassSettings::isNoLineWrapping, QtPassSettings::isStartMinimized, QtPassSettings::isTemplateAllFields, QtPassSettings::isUseAutoclear, QtPassSettings::isUseAutoclearPanel, QtPassSettings::isUseGit, QtPassSettings::isUseGrepSearch, QtPassSettings::isUseMonospace, QtPassSettings::isUseOtp, QtPassSettings::isUsePass, QtPassSettings::isUsePwgen, QtPassSettings::isUseQrencode, QtPassSettings::isUseSelection, QtPassSettings::isUseSymbols, QtPassSettings::isUseTemplate, QtPassSettings::isUseTrayIcon, setPasswordConfiguration, setPwgenPath, useAutoclear, useAutoclearPanel, useGit, useGrepSearch, useOtp, usePwgen, useQrencode, useSelection, useTemplate, useTrayIcon.
Referenced by ConfigDialog.
ConfigDialog::~ConfigDialog() override
ConfigDialog::~ConfigDialog config destructor, makes sure the mainWindow knows about git, gpg and pass executables.
References QtPassSettings::setGitExecutable, QtPassSettings::setGpgExecutable, QtPassSettings::setPassExecutable.
void ConfigDialog::useSelection(bool useSelection)
Enable or disable clipboard selection mode.
ConfigDialog::useSelection set the clipboard type use from MainWindow. useSelection true to enable selection mode. useSelection
References useSelection.
Referenced by ConfigDialog, useSelection.
void ConfigDialog::useAutoclear(bool useAutoclear)
Enable or disable autoclear of the clipboard.
ConfigDialog::useAutoclear set the clipboard autoclear use from MainWindow. useAutoclear true to enable autoclear. useAutoclear
References useAutoclear.
Referenced by ConfigDialog, useAutoclear.
void ConfigDialog::useAutoclearPanel(bool useAutoclearPanel)
Enable or disable autoclear of the panel.
ConfigDialog::useAutoclearPanel set the panel autoclear use from MainWindow. useAutoclearPanel true to enable panel autoclear. useAutoclearPanel
References useAutoclearPanel.
Referenced by ConfigDialog, useAutoclearPanel.
QHash< QString, QHash< QString, QString > > ConfigDialog::getProfiles()
Return all configured profiles.
ConfigDialog::getProfiles return profile list. Hash of profile name to key-value settings map.
void ConfigDialog::wizard()
Run the first-time setup wizard.
ConfigDialog::wizard first-time use wizard.
References Util::configIsValid.
void ConfigDialog::genKey(const QString &batch, QDialog *dialog)
Start GPG key generation.
ConfigDialog::genKey tunnel function to make MainWindow generate a gpg key pair. batch GPG batch parameter string. dialog Parent dialog to return to after generation. batch dialog
void ConfigDialog::useTrayIcon(bool useSystray)
Show or hide the system tray icon.
ConfigDialog::useTrayIcon set preference for using trayicon. Enable or disable related checkboxes accordingly. useSystray true to enable the tray icon. useSystray
Referenced by ConfigDialog.
void ConfigDialog::useGit(bool useGit)
Enable or disable git integration.
ConfigDialog::useGit set preference for using git. useGit true to enable git. useGit
References useGit.
Referenced by ConfigDialog, useGit.
void ConfigDialog::useOtp(bool useOtp)
Enable or disable OTP support.
ConfigDialog::useOtp set preference for using otp plugin. useOtp true to enable OTP. useOtp
References useOtp.
Referenced by ConfigDialog, useOtp.
void ConfigDialog::useGrepSearch(bool useGrepSearch)
Enable or disable grep content search.
useGrepSearch true to enable grep search.
References useGrepSearch.
Referenced by ConfigDialog, useGrepSearch.
void ConfigDialog::useQrencode(bool useQrencode)
Enable or disable QR code display.
ConfigDialog::useQrencode set preference for using qrencode plugin. useQrencode true to enable qrencode. useQrencode
References useQrencode.
Referenced by ConfigDialog, useQrencode.
void ConfigDialog::setPwgenPath(const QString &path)
Set the path to the pwgen executable.
ConfigDialog::setPwgenPath set pwgen executable path. Enable or disable related options in the interface. path Path to pwgen. pwgen
Referenced by ConfigDialog.
void ConfigDialog::usePwgen(bool usePwgen)
Enable or disable pwgen-based password generation.
ConfigDialog::usePwgen set preference for using pwgen (can be overruled by empty pwgenPath). enable or disable related options in the interface via ConfigDialog::on_checkBoxUsePwgen_clicked. usePwgen true to use pwgen. usePwgen
References usePwgen.
Referenced by ConfigDialog, usePwgen.
void ConfigDialog::setPasswordConfiguration(const PasswordConfiguration &config)
Apply a password configuration to the dialog controls.
config Configuration to display.
References PasswordConfiguration::Characters, PasswordConfiguration::CUSTOM, PasswordConfiguration::length, PasswordConfiguration::selected.
Referenced by ConfigDialog.
PasswordConfiguration ConfigDialog::getPasswordConfiguration()
Read the current password configuration from the dialog controls.
Current PasswordConfiguration.
References PasswordConfiguration::Characters, PasswordConfiguration::CUSTOM, PasswordConfiguration::length, PasswordConfiguration::selected.
void ConfigDialog::useTemplate(bool useTemplate)
Enable or disable password file templating.
ConfigDialog::useTemplate set preference for using templates. useTemplate true to enable the template. useTemplate
References useTemplate.
Referenced by ConfigDialog, useTemplate.
void ConfigDialog::closeEvent(QCloseEvent *event) override
ConfigDialog::closeEvent close this window.
event
References QtPassSettings::setDialogGeometry, QtPassSettings::setDialogMaximized, QtPassSettings::setDialogPos, QtPassSettings::setDialogSize.
void ConfigDialog::on_accepted()
void ConfigDialog::on_autodetectButton_clicked()
void ConfigDialog::on_radioButtonNative_clicked()
ConfigDialog::on_radioButtonNative_clicked wrapper for ConfigDialog::setGroupBoxState().
void ConfigDialog::on_radioButtonPass_clicked()
ConfigDialog::on_radioButtonPass_clicked wrapper for ConfigDialog::setGroupBoxState().
void ConfigDialog::on_toolButtonGit_clicked()
ConfigDialog::on_toolButtonGit_clicked get git application. Enable checkboxes if found.
void ConfigDialog::on_toolButtonGpg_clicked()
ConfigDialog::on_toolButtonGpg_clicked get gpg application.
void ConfigDialog::on_pushButtonGenerateKey_clicked()
ConfigDialog::on_pushButtonGenerateKey_clicked open keygen dialog.
void ConfigDialog::on_toolButtonPwgen_clicked()
ConfigDialog::on_toolButtonPwgen_clicked enable or disable related options in the interface.
void ConfigDialog::on_toolButtonPass_clicked()
ConfigDialog::on_toolButtonPass_clicked get pass application.
void ConfigDialog::on_toolButtonStore_clicked()
ConfigDialog::on_toolButtonStore_clicked get .password-store location.
void ConfigDialog::on_comboBoxClipboard_activated(int)
ConfigDialog::on_comboBoxClipboard_activated show and hide options.
index of selectbox (0 = no clipboard).
void ConfigDialog::on_passwordCharTemplateSelector_activated(int)
ConfigDialog::on_passwordCharTemplateSelector_activated sets the passwordChar Template combo box to the desired entry.
entry of
void ConfigDialog::on_checkBoxSelection_clicked()
ConfigDialog::on_checkBoxSelection_clicked checkbox clicked, update state via ConfigDialog::on_comboBoxClipboard_activated.
void ConfigDialog::on_checkBoxAutoclear_clicked()
ConfigDialog::on_checkBoxAutoclear_clicked checkbox clicked, update state via ConfigDialog::on_comboBoxClipboard_activated.
void ConfigDialog::on_checkBoxAutoclearPanel_clicked()
ConfigDialog::on_checkBoxAutoclearPanel_clicked enable and disable options based on autoclear use.
void ConfigDialog::on_addButton_clicked()
ConfigDialog::on_addButton_clicked add a profile row.
void ConfigDialog::on_deleteButton_clicked()
ConfigDialog::on_deleteButton_clicked remove a profile row.
void ConfigDialog::on_profileTable_cellDoubleClicked(int row, int column)
ConfigDialog::on_profileTable_cellDoubleClicked open folder browser for path column (column 1).
void ConfigDialog::on_checkBoxUseTrayIcon_clicked()
ConfigDialog::on_checkBoxUseTrayIcon_clicked enable and disable related checkboxes.
void ConfigDialog::on_checkBoxUseGit_clicked()
ConfigDialog::on_checkBoxUseGit_clicked enable or disable related checkboxes.
void ConfigDialog::on_checkBoxUsePwgen_clicked()
ConfigDialog::on_checkBoxUsePwgen_clicked enable or disable related options in the interface.
void ConfigDialog::on_checkBoxUseTemplate_clicked()
ConfigDialog::on_checkBoxUseTemplate_clicked enable or disable the template field and options.
void ConfigDialog::onProfileTableItemChanged(QTableWidgetItem *item)
QStringList ConfigDialog::getSecretKeys()
ConfigDialog::getSecretKeys get list of secret/private keys.
QStringList keys
void ConfigDialog::setGitPath(const QString &)
ConfigDialog::setGitPath set the git executable path. Make sure the checkBoxUseGit is updated.
path
void ConfigDialog::setProfiles(QHash< QString, QHash< QString, QString > >, const QString &)
ConfigDialog::setProfiles set the profiles and chosen profile from MainWindow.
profiles profile
void ConfigDialog::usePass(bool usePass)
ConfigDialog::usePass set wether or not we want to use pass. Update radio buttons accordingly.
usePass
void ConfigDialog::setGroupBoxState()
ConfigDialog::setGroupBoxState update checkboxes.
QString ConfigDialog::selectExecutable()
ConfigDialog::selectExecutable pop-up to choose an executable.
QString ConfigDialog::selectFolder()
ConfigDialog::selectFolder pop-up to choose a folder.
void ConfigDialog::criticalMessage(const QString &title, const QString &text)
ConfigDialog::criticalMessage wrapper for showing critical messages in a popup.
title text
bool ConfigDialog::isPassOtpAvailable()
bool ConfigDialog::isQrencodeAvailable()
void ConfigDialog::validate(QTableWidgetItem *item=nullptr)
bool ConfigDialog::checkGpgExistence()
bool ConfigDialog::checkSecretKeys()
bool ConfigDialog::checkPasswordStore()
void ConfigDialog::handleGpgIdFile()
void ConfigDialog::initializeNewProfiles(const QHash< QString, QHash< QString, QString > > &existingProfiles)
Initialize new profiles that need pass/git initialization.
existingProfiles The profiles that existed before the dialog was opened.