Pass
using Pass::PROCESS = Enums::PROCESS
bool Pass::wrapperRunning
QStringList Pass::env
Executor Pass::exec
Referenced by executeWrapper, ImitatePass::finished, ImitatePass::Grep, Pass, updateEnv.
Pass::Pass()
Construct a Pass instance.
Pass::Pass wrapper for using either pass or the pass imitation.
References exec, finished, Executor::starting, startingExecuteWrapper.
void Pass::init()
Initialize the Pass instance.
Initializes the pass wrapper environment.
References QtPassSettings::getGpgHome.
Pass::~Pass() override=default
virtual void Pass::GitInit()=0
Initialize Git repository in password store.
virtual void Pass::GitPull()=0
Pull changes from remote Git repository.
virtual void Pass::GitPull_b()=0
Pull with rebase from remote.
virtual void Pass::GitPush()=0
Push changes to remote Git repository.
virtual void Pass::Show(QString file)=0
Show decrypted password file.
file Path to password file relative to store root.
virtual void Pass::OtpGenerate(QString file)=0
Generate OTP for password file.
file Path to password file.
virtual void Pass::Insert(QString file, QString value, bool force)=0
Insert or update password.
file Path to password file. value Password content to store. force Overwrite existing file.
virtual void Pass::Remove(QString file, bool isDir)=0
Remove password file or directory.
file Path to remove. isDir true if removing a directory.
virtual void Pass::Move(const QString srcDir, const QString dest, const bool force=false)=0
Move password file or directory.
srcDir Source path. dest Destination path. force Overwrite existing.
virtual void Pass::Copy(const QString srcDir, const QString dest, const bool force=false)=0
Copy password file or directory.
srcDir Source path. dest Destination path. force Overwrite existing.
virtual void Pass::Init(QString path, const QList< UserInfo > &users)=0
Initialize new password store.
path Root of password store. users List of recipient GPG keys.
virtual void Pass::Grep(QString pattern, bool caseInsensitive=false)=0
Search password content for a pattern.
pattern Search pattern (regular expression). caseInsensitive true for case-insensitive search.
QString Pass::generatePassword(unsigned int length, const QString &charset)
Generate random password.
Pass::Generate use either pwgen or internal password generator. length Password length. charset Character set to use. Generated password. length of the desired password charset to use for generation the password
References PasswordConfiguration::ALLCHARS, critical, Executor::executeBlocking, generateRandomPassword, QtPassSettings::getPasswordConfiguration, QtPassSettings::getPwgenExecutable, QtPassSettings::isAvoidCapitals, QtPassSettings::isAvoidNumbers, QtPassSettings::isLessRandom, QtPassSettings::isUsePwgen, QtPassSettings::isUseSymbols.
void Pass::GenerateGPGKeys(QString batch)
Generate GPG keys using batch script.
Pass::GenerateGPGKeys internal gpg keypair generator . . batch GPG batch script content. batch GnuPG style configuration string
References ResolvedGpgconfCommand::arguments, Executor::executeBlocking, executeWrapper, QtPassSettings::getGpgExecutable, GPG_GENKEYS, ResolvedGpgconfCommand::program, resolveGpgconfCommand.
QList< UserInfo > Pass::listKeys(QStringList keystrings, bool secret=false)
List GPG keys matching patterns.
Pass::listKeys list users. keystrings List of search patterns. secret Include secret keys. List of matching keys. keystrings secret list private keys QList<UserInfo> users
References AS_CONST, Executor::executeBlocking, QtPassSettings::getGpgExecutable, parseGpgColonOutput.
Referenced by listKeys.
QList< UserInfo > Pass::listKeys(const QString &keystring="", bool secret=false)
List GPG keys.
Pass::listKeys list users. keystring Search pattern. secret Include secret keys. List of matching keys. keystring secret list private keys QList<UserInfo> users
References listKeys.
void Pass::updateEnv()
Update environment for subprocesses.
Update the process environment used for executing external commands. Updates environment entries for PASSWORD_STORE_SIGNING_KEY, PASSWORD_STORE_DIR, PASSWORD_STORE_GENERATED_LENGTH, and PASSWORD_STORE_CHARACTER_SET based on current settings, then applies the environment to the internal executor.
References exec, QtPassSettings::getPassSigningKey, QtPassSettings::getPassStore, QtPassSettings::getPasswordConfiguration, PasswordConfiguration::length, setEnvVar.
bool Pass::gpgSupportsEd25519()
Check if GPG supports Ed25519 encryption.
Pass::gpgSupportsEd25519 check if GPG supports ed25519 (ECC) GPG 2.1+ supports ed25519 which is much faster for key generation. true if Ed25519 is supported. true if ed25519 is supported
References Executor::executeBlocking, QtPassSettings::getGpgExecutable.
Referenced by getDefaultKeyTemplate.
QString Pass::getDefaultKeyTemplate()
Get default key template for new GPG keys.
Pass::getDefaultKeyTemplate return default key generation template Uses ed25519 if supported, otherwise falls back to RSA. Default template string. GPG batch template string
References gpgSupportsEd25519.
Referenced by KeygenDialog::KeygenDialog.
ResolvedGpgconfCommand Pass::resolveGpgconfCommand(const QString &gpgPath)
Resolve the gpgconf command to kill agents.
gpgPath Path to gpg executable. Resolved command with program and arguments.
Referenced by GenerateGPGKeys.
QString Pass::getGpgIdPath(const QString &for_file)
Get .gpg-id file path for a password file.
Pass::getGpgIdPath return gpgid file path for some file (folder). for_file Path to password file. Path to .gpg-id file. for_file which file (folder) would you like the gpgid file path for. path to the gpgid file.
References QtPassSettings::getPassStore.
Referenced by getRecipientList, ImitatePass::Insert, ImitatePass::verifyGpgIdForDir.
QStringList Pass::getRecipientList(const QString &for_file)
Get list of recipients for a password file.
Pass::getRecipientList return list of gpg-id's to encrypt for. for_file Path to password file. List of recipient key IDs. for_file which file (folder) would you like recipients for recipients gpg-id contents
References getGpgIdPath, Util::isValidKeyId.
Referenced by getRecipientString, ImitatePass::Insert, ImitatePass::verifyGpgIdForDir.
QStringList Pass::getRecipientString(const QString &for_file, const QString &separator=" ", int *count=nullptr)
Get recipients as string.
Pass::getRecipientString formatted string for use with GPG. for_file Path to password file. separator Separator between recipients. count Pointer to store recipient count. List of recipient key IDs. for_file which file (folder) would you like recipients for separator formating separator eg: " -r " count recipient string
References getRecipientList.
void Pass::executeWrapper(PROCESS id, const QString &app, const QStringList &args, bool readStdout=true, bool readStderr=true)
Execute external wrapper command.
Executes a wrapper command. id Process identifier. app Executable path. args Command arguments. readStdout Capture stdout. readStderr Capture stderr. id Process ID app Application to execute args Arguments readStdout Whether to read stdout readStderr Whether to read stderr
References executeWrapper.
Referenced by ImitatePass::executeWrapper, executeWrapper, GenerateGPGKeys.
QString Pass::generateRandomPassword(const QString &charset, unsigned int length)
Generate random password from charset.
Generates a random password from the given charset. charset Character set. length Password length. Generated password. charset Characters to use in the password length Desired password length Generated password string
References boundedRandom.
Referenced by generatePassword.
quint32 Pass::boundedRandom(quint32 bound)
Generate random number in range.
Generates a random number bounded by the given value. bound Upper bound (exclusive). Random number. bound Upper bound (exclusive) Random number in range [0, bound)
Referenced by generateRandomPassword.
void Pass::setEnvVar(const QString &key, const QString &value)
Set or remove an environment variable.
Pass::setEnvVar set or remove a single environment variable. key Variable name including trailing '='. value New value; empty string removes the variable. key Variable name including trailing '=' (e.g. "FOO="). value Value to set; pass an empty string to remove the variable. Set or remove a single environment variable in the local env list. The provided key must include a trailing '=' (e.g. "FOO="). Existing entries whose text begins with the given key are removed before the new value is applied. If value is non-empty the pair "key+value" is appended; if value is empty the variable is removed. The function asserts if key does not end with '='; if the assertion is not active it will emit a warning and return without modifying env. key Environment variable name with trailing '=' (anchors the lookup). value Value to set for the variable; an empty string unsets the variable.
Referenced by updateEnv.
void Pass::executeWrapper(PROCESS id, const QString &app, const QStringList &args, QString input, bool readStdout=true, bool readStderr=true)
Execute wrapper with input.
id Process identifier. app Executable path. args Command arguments. input Input to pass to stdin. readStdout Capture stdout. readStderr Capture stderr.
References dbg, exec, QtPassSettings::getPassStore.
void Pass::finished(int id, int exitCode, const QString &out, const QString &err)
Handle process completion.
Pass::processFinished reemits specific signal based on what process has finished. id Process identifier. exitCode Process exit code. out Standard output. err Standard error. id id of Pass process that was scheduled and finished exitCode return code of a process out output generated by process(if capturing was requested, empty otherwise) err error output generated by process(if capturing was requested, or error occurred)
Referenced by ImitatePass::finished, Pass.
void Pass::handleProcessError(PROCESS pid, int exitCode, const QString &out, const QString &err)
void Pass::handleGrepError(int exitCode, const QString &err)
QString Pass::formatInsertError(const QString &friendly, const QString &err)
void Pass::emitProcessFinishedSignal(PROCESS pid, const QString &out, const QString &err)
Emit the appropriate finished signal for a completed subprocess.
Emits a specific Qt signal corresponding to the given process identifier; for grep results the stdout is parsed into a list of matches before emitting. pid The process identifier indicating which finished signal to emit. out Standard output produced by the process. err Standard error produced by the process.
void Pass::error(QProcess::ProcessError)
Emitted when a process error occurs.
void Pass::startingExecuteWrapper()
Emitted before executing a command.
Referenced by Pass.
void Pass::statusMsg(const QString &, int)
Emit status message.
Message text. Timeout in ms.
Referenced by ImitatePass::createBackupCommit, ImitatePass::reencryptPath.
void Pass::critical(const QString &, const QString &)
Emit critical error.
title Error title. message Error message.
Referenced by ImitatePass::createBackupCommit, generatePassword, ImitatePass::Init, ImitatePass::Insert, ImitatePass::reencryptPath, ImitatePass::reencryptSingleFile, ImitatePass::signGpgIdFile, ImitatePass::verifyGpgIdForDir, ImitatePass::writeGpgIdFile.
void Pass::processErrorExit(int exitCode, const QString &err)
Emitted on process error exit.
Referenced by PasswordDialog::PasswordDialog.
void Pass::finishedAny(const QString &, const QString &)
Emitted when any operation finishes.
void Pass::finishedGitInit(const QString &, const QString &)
Emitted when Git init finishes.
void Pass::finishedGitPull(const QString &, const QString &)
Emitted when Git pull finishes.
void Pass::finishedGitPush(const QString &, const QString &)
Emitted when Git push finishes.
void Pass::finishedShow(const QString &)
Emitted when show finishes.
Referenced by PasswordDialog::PasswordDialog, PasswordDialog::PasswordDialog.
void Pass::finishedOtpGenerate(const QString &)
Emitted when OTP generation finishes.
void Pass::finishedInsert(const QString &, const QString &)
Emitted when insert finishes.
void Pass::finishedRemove(const QString &, const QString &)
Emitted when remove finishes.
void Pass::finishedInit(const QString &, const QString &)
Emitted when init finishes.
void Pass::finishedMove(const QString &, const QString &)
Emitted when move finishes.
void Pass::finishedCopy(const QString &, const QString &)
Emitted when copy finishes.
void Pass::finishedGenerate(const QString &, const QString &)
Emitted when generate finishes.
void Pass::finishedGenerateGPGKeys(const QString &, const QString &)
Emitted when GPG key generation finishes.
void Pass::finishedGrep(const QList< QPair< QString, QStringList > > &results)
Emitted when grep finishes with matching results.
Referenced by ImitatePass::Grep.