TrayIcon
QAction* TrayIcon::showAction
QAction* TrayIcon::hideAction
QAction* TrayIcon::minimizeAction
QAction* TrayIcon::maximizeAction
QAction* TrayIcon::restoreAction
QAction* TrayIcon::quitAction
QSystemTrayIcon* TrayIcon::sysTrayIcon
QMenu* TrayIcon::trayIconMenu
QMainWindow* TrayIcon::parentwin
bool TrayIcon::isAllocated
TrayIcon::TrayIcon(QMainWindow *parent)
Construct a TrayIcon associated with the given main window.
TrayIcon::TrayIcon use a (system) tray icon with a nice QtPass logo on it (currently) only Quits. parent Pointer to the QMainWindow this tray icon controls. parent
References dbg, iconActivated.
void TrayIcon::showMessage(const QString &title, const QString &msg, int time)
Display a transient notification message via the tray icon.
TrayIcon::showMessage show a systray message for notification. title Title text of the notification. msg Body text of the notification. time Duration to display the notification in milliseconds. title msg time
Referenced by iconActivated.
void TrayIcon::setVisible(bool visible)
Show or hide the tray icon and its associated UI.
TrayIcon::setVisible show or hide the icon. visible true to make the tray icon visible, false to hide it. visible
bool TrayIcon::getIsAllocated()
Returns true if tray resources have been allocated and initialized.
TrayIcon::getIsAllocated return if TrayIcon is allocated.
void TrayIcon::showHideParent()
Toggle the visibility of the associated main window.
TrayIcon::showHideParent toggle app visibility.
Referenced by iconActivated.
void TrayIcon::iconActivated(QSystemTrayIcon::ActivationReason reason)
Handle activation events from the system tray icon.
TrayIcon::iconActivated you clicked on the trayicon. reason The activation reason provided by QSystemTrayIcon. reason
References showHideParent, showMessage.
Referenced by TrayIcon.
void TrayIcon::createActions()
TrayIcon::createActions setup the signals.
void TrayIcon::createTrayIcon()
TrayIcon::createTrayIcon set up menu.