ImitatePass
friend class tst_util
References tst_util.
Referenced by tst_util.
int ImitatePass::m_grepSeq
QList<QThread *> ImitatePass::m_grepThreads
bool ImitatePass::verifyGpgIdFile(const QString &file)
Verify .gpg-id file exists and is valid.
ImitatePass::verifyGpgIdFile verify detached gpgid file signature. file Path to check. true if valid. file which gpgid file. was verification successful?
References dbg, Executor::executeBlocking, QtPassSettings::getGpgExecutable, QtPassSettings::getPassSigningKey.
Referenced by Insert, signGpgIdFile, verifyGpgIdForDir.
bool ImitatePass::removeDir(const QString &dirName)
Remove directory recursively.
ImitatePass::removeDir delete folder recursive. dirName Directory path. true if removed. dirName which folder. was removal successful?
References removeDir.
Referenced by removeDir.
bool ImitatePass::checkSigningKeys(const QStringList &signingKeys)
Check if signing keys are valid.
ImitatePass::Init initialize pass repository. signingKeys List of key IDs. true if all keys valid. path path in which new password-store will be created users list of users who shall be able to decrypt passwords in path
References dbg, Executor::executeBlocking, QtPassSettings::getGpgExecutable.
Referenced by Init.
void ImitatePass::writeGpgIdFile(const QString &gpgIdFile, const QList< UserInfo > &users)
Write recipients to .gpg-id file.
Writes the selected users' GPG key IDs to a .gpg-id file. gpgIdFile Path to .gpg-id file. users List of recipients. Opens the specified file for writing, stores the key ID of each enabled user on a separate line, and warns if none of the selected users has a secret key available. QString &gpgIdFile - Path to the .gpg-id file to be written. QList<UserInfo> &users - List of users to evaluate and write to the file. void - This function does not return a value.
References Pass::critical.
Referenced by Init.
bool ImitatePass::signGpgIdFile(const QString &gpgIdFile, const QStringList &signingKeys)
Sign .gpg-id file with signing keys.
gpgIdFile Path to .gpg-id file. signingKeys Key IDs to sign with. true on success, false on failure.
References Pass::critical, dbg, Executor::executeBlocking, QtPassSettings::getGpgExecutable, verifyGpgIdFile.
Referenced by Init.
void ImitatePass::gitAddGpgId(const QString &gpgIdFile, const QString &gpgIdSigFile, bool addFile, bool addSigFile)
Add .gpg-id to git staging.
gpgIdFile .gpg-id file path. gpgIdSigFile Signature file path. addFile Stage .gpg-id file. addSigFile Stage signature file.
References Util::endsWithGpg, executeGit, GIT_ADD, gitCommit.
Referenced by Init.
bool ImitatePass::verifyGpgIdForDir(const QString &file, QStringList &gpgIdFilesVerified, QStringList &gpgId)
Verify .gpg-id file for a directory.
ImitatePass::reencryptPath reencrypt all files under the chosen directory. file Password file path. gpgIdFilesVerified List of already verified .gpg-id files. gpgId Output parameter for recipient key IDs. true on success, false on failure. This is still quite experimental.. dir
References Pass::critical, Pass::getGpgIdPath, Pass::getRecipientList, verifyGpgIdFile.
Referenced by reencryptPath.
bool ImitatePass::createBackupCommit()
Create git backup commit before re-encryption.
true if backup created or not needed, false if backup failed.
References Pass::critical, Executor::executeBlocking, QtPassSettings::getGitExecutable, QtPassSettings::isUseGit, Pass::statusMsg.
Referenced by reencryptPath.
QStringList ImitatePass::getKeysFromFile(const QString &fileName)
Read recipients from file.
fileName Path to file. List of key IDs.
References Executor::executeBlocking, QtPassSettings::getGpgExecutable, Util::newLinesRegex.
Referenced by reencryptPath.
bool ImitatePass::reencryptSingleFile(const QString &fileName, const QStringList &recipients)
Re-encrypt single file with new recipients.
fileName File to re-encrypt. recipients New recipient key IDs. true on success, false on failure.
References Pass::critical, dbg, Util::endsWithGpg, Executor::executeBlocking, QtPassSettings::getGitExecutable, QtPassSettings::getGpgExecutable, QtPassSettings::getPassStore, QtPassSettings::isUseGit, QtPassSettings::isUseWebDav.
Referenced by reencryptPath.
QString ImitatePass::resolveMoveDestination(const QString &src, const QString &dest, bool force)
Resolve destination for move operation.
src Source path. dest Destination path. force Overwrite existing. Resolved destination path.
References dbg.
Referenced by Move.
void ImitatePass::finished(int id, int exitCode, const QString &out, const QString &err) override
Handle process completion.
ImitatePass::finished this function is overloaded to ensure identical behaviour to RealPass ie. only PASS_* processes are visible inside Pass::finish, so that interface-wise it all looks the same. id exitCode out err
References dbg, Pass::exec, Pass::finished, INVALID, simpleTransaction::transactionIsOver.
void ImitatePass::executeWrapper(PROCESS id, const QString &app, const QStringList &args, QString input, bool readStdout=true, bool readStderr=true) override
Execute command wrapper.
executeWrapper overrided so that every execution is a transaction id app args input readStdout readStderr
References Pass::executeWrapper, simpleTransaction::transactionAdd.
Referenced by executeGit, executeGpg.
void ImitatePass::executeMoveGit(const QString &src, const QString &destFile, bool force)
Execute git move operation.
src Source path. destFile Destination path. force Overwrite existing.
References Util::endsWithGpg, executeGit, QtPassSettings::getPassStore, GIT_MOVE, gitCommit.
Referenced by Move.
void ImitatePass::gitCommit(const QString &file, const QString &msg)
Commit changes to git.
ImitatePass::gitCommit commit a file to git with an appropriate commit message. file Changed file path. msg Commit message. file msg
References executeGit, GIT_COMMIT.
Referenced by Copy, executeMoveGit, gitAddGpgId, Insert, Remove.
void ImitatePass::executeGit(PROCESS id, const QStringList &args, QString input=QString(), bool readStdout=true, bool readStderr=true)
Execute git command.
ImitatePass::executeGit easy wrapper for running git commands. id Process identifier. args Git arguments. input Input to stdin. readStdout Capture stdout. readStderr Capture stderr. args
References executeWrapper, QtPassSettings::getGitExecutable.
Referenced by Copy, executeMoveGit, gitAddGpgId, gitCommit, GitInit, GitPull, GitPush, Insert, Remove.
void ImitatePass::executeGpg(PROCESS id, const QStringList &args, QString input=QString(), bool readStdout=true, bool readStderr=true)
Execute GPG command.
ImitatePass::executeGpg easy wrapper for running gpg commands. id Process identifier. args GPG arguments. input Input to stdin. readStdout Capture stdout. readStderr Capture stderr. args
References executeWrapper, QtPassSettings::getGpgExecutable.
Referenced by Insert, Show.
ImitatePass::ImitatePass()
Construct ImitatePass instance.
ImitatePass::ImitatePass for situations when pass is not available we imitate the behavior of pass https://www.passwordstore.org/.
ImitatePass::~ImitatePass() override
Destructor.
void ImitatePass::GitInit() override
Initialize Git repository.
ImitatePass::GitInit git init wrapper.
References executeGit, QtPassSettings::getPassStore, GIT_INIT.
void ImitatePass::GitPull() override
Pull from remote.
ImitatePass::GitPull git pull wrapper.
References executeGit, GIT_PULL.
void ImitatePass::GitPull_b() override
Pull with rebase.
ImitatePass::GitPull_b git pull wrapper.
References Executor::executeBlocking, QtPassSettings::getGitExecutable.
Referenced by reencryptPath.
void ImitatePass::GitPush() override
Push to remote.
ImitatePass::GitPush git push wrapper.
References executeGit, GIT_PUSH, QtPassSettings::isUseGit.
Referenced by reencryptPath.
void ImitatePass::Show(QString file) override
Show decrypted password.
ImitatePass::Show shows content of file.
References executeGpg, QtPassSettings::getPassStore, PASS_SHOW.
void ImitatePass::OtpGenerate(QString file) override
Generate OTP.
ImitatePass::OtpGenerate generates an otp code.
References dbg.
void ImitatePass::Insert(QString file, QString newValue, bool overwrite=false) override
Insert new password.
ImitatePass::Insert create new file with encrypted content. file file to be created newValue value to be stored in file overwrite whether to overwrite existing file
References Pass::critical, Util::endsWithGpg, executeGit, executeGpg, Pass::getGpgIdPath, QtPassSettings::getPassStore, Pass::getRecipientList, GIT_ADD, gitCommit, QtPassSettings::isUseGit, QtPassSettings::isUseWebDav, PASS_INSERT, verifyGpgIdFile.
void ImitatePass::Remove(QString file, bool isDir=false) override
Remove password.
ImitatePass::Remove custom implementation of "pass remove".
References Util::endsWithGpg, executeGit, QtPassSettings::getPassStore, GIT_RM, gitCommit, QtPassSettings::isUseGit, PASS_REMOVE.
void ImitatePass::Init(QString path, const QList< UserInfo > &users) override
Initialize store.
References checkSigningKeys, Pass::critical, QtPassSettings::getGitExecutable, QtPassSettings::getPassSigningKey, gitAddGpgId, QtPassSettings::isAddGPGId, QtPassSettings::isUseGit, QtPassSettings::isUseWebDav, PASS_INIT, reencryptPath, signGpgIdFile, writeGpgIdFile.
void ImitatePass::reencryptPath(const QString &dir)
Re-encrypt entire directory.
Re-encrypts all .gpg files under the given directory using the verified GPG key configuration for each folder. dir Directory path. This method optionally pulls the latest changes before starting, creates a backup commit, verifies .gpg-id files per directory, and re-encrypts files whose current recipients do not match the expected keys. It emits progress, status, and error signals throughout the process, and optionally pushes the updated password-store when finished. dir - Root directory to scan recursively for .gpg files. void
References createBackupCommit, Pass::critical, endReencryptPath, getKeysFromFile, GitPull_b, GitPush, QtPassSettings::isAutoPull, QtPassSettings::isAutoPush, reencryptSingleFile, startReencryptPath, Pass::statusMsg, verifyGpgIdForDir.
Referenced by Copy, Init.
void ImitatePass::Move(const QString src, const QString dest, const bool force=false) override
Move password file.
References dbg, executeMoveGit, QtPassSettings::isUseGit, PASS_MOVE, resolveMoveDestination.
void ImitatePass::Copy(const QString src, const QString dest, const bool force=false) override
Copy password file.
References executeGit, GIT_COPY, gitCommit, QtPassSettings::isUseGit, PASS_COPY, reencryptPath.
void ImitatePass::Grep(QString pattern, bool caseInsensitive=false) override
Search all password content by GPG-decrypting each .gpg file.
Pattern is interpreted as a QRegularExpression (PCRE-like), which differs from RealPass::Grep which uses system pass grep (POSIX BRE via grep). The same pattern may produce different matches across the two backends. pattern Search pattern (QRegularExpression). caseInsensitive true for case-insensitive search. Runs a background thread to avoid blocking the UI. Results are emitted on the main thread via QMetaObject::invokeMethod. A sequence counter discards results from superseded searches.
References Pass::exec, Pass::finishedGrep, QtPassSettings::getGpgExecutable, QtPassSettings::getPassStore.
void ImitatePass::startReencryptPath()
Emitted before starting re-encryption.
Referenced by reencryptPath.
void ImitatePass::endReencryptPath()
Emitted after finishing re-encryption.
Referenced by reencryptPath.
QStringList ImitatePass::grepMatchFile(const QStringList &env, const QString &gpgExe, const QString &filePath, const QRegularExpression &rx)
Decrypt one .gpg file and return lines matching rx.
QList< QPair< QString, QStringList > > ImitatePass::grepScanStore(const QStringList &env, const QString &gpgExe, const QString &storeDir, const QRegularExpression &rx)
Walk the store, decrypt every .gpg file, collect matches.