Executor
QQueue<execQueueItem> Executor::m_execQueue
QProcess Executor::m_process
bool Executor::running
void Executor::executeNext()
Executor::executeNext consumes executable tasks from the queue.
void Executor::startProcess(const QString &app, const QStringList &args)
Executor::startProcess starts the internal process, handling WSL prefixes.
app Executable path (may start with "wsl "). args Arguments to pass to the executable.
void Executor::startProcessBlocking(QProcess &internal, const QString &app, const QStringList &args)
Executor::startProcessBlocking starts a given process, handling WSL prefixes.
internal QProcess reference to start. app Executable path (may start with "wsl "). args Arguments to pass to the executable.
Executor::Executor(QObject *parent=nullptr)
Executor::Executor executes external applications.
parent
References Executor, starting.
Referenced by Executor.
void Executor::execute(int id, const QString &app, const QStringList &args, bool readStdout, bool readStderr=true)
Executor::execute execute an app.
id app args readStdout readStderr
References execute.
Referenced by execute, execute, execute.
void Executor::execute(int id, const QString &workDir, const QString &app, const QStringList &args, bool readStdout, bool readStderr=true)
Executor::execute executes an app from a workDir.
id workDir app args readStdout readStderr
References execute.
void Executor::execute(int id, const QString &app, const QStringList &args, QString input=QString(), bool readStdout=false, bool readStderr=true)
Executor::execute an app, takes input and presents it as stdin.
id app args input readStdout readStderr
References execute.
void Executor::execute(int id, const QString &workDir, const QString &app, const QStringList &args, QString input=QString(), bool readStdout=false, bool readStderr=true)
Executor::execute executes an app from a workDir, takes input and presents it as stdin.
id workDir app args input readStdout readStderr
References dbg.
void Executor::setEnvironment(const QStringList &env)
Executor::setEnvironment set environment variables for executor processes.
env
QStringList Executor::environment() const
Return the environment passed to child processes.
Environment as a list of "KEY=value" strings.
int Executor::cancelNext()
Executor::cancelNext cancels execution of first process in queue if it's not already running.
id of the cancelled process or -1 on error
int Executor::executeBlocking(const QString &app, const QStringList &args, const QString &input=QString(), QString *process_out=nullptr, QString *process_err=nullptr)
Executor::executeBlocking blocking version of the executor, takes input and presents it as stdin.
app args input process_out process_err Note: Returning error code instead of throwing to maintain compatibility with the existing error handling pattern used throughout QtPass.
References dbg.
Referenced by ImitatePass::checkSigningKeys, Util::configIsValid, ImitatePass::createBackupCommit, executeBlocking, Util::findBinaryInPath, Pass::GenerateGPGKeys, Pass::generatePassword, ImitatePass::getKeysFromFile, ImitatePass::GitPull_b, RealPass::GitPull_b, Pass::gpgSupportsEd25519, Pass::listKeys, ImitatePass::reencryptSingleFile, ImitatePass::signGpgIdFile, ImitatePass::verifyGpgIdFile.
int Executor::executeBlocking(const QString &app, const QStringList &args, QString *process_out, QString *process_err=nullptr)
Executor::executeBlocking blocking version of the executor.
app args process_out process_err
References executeBlocking.
int Executor::executeBlocking(const QStringList &env, const QString &app, const QStringList &args, QString *process_out=nullptr, QString *process_err=nullptr)
Executor::executeBlocking blocking version with custom environment.
env Environment variables to set app Executable path args Arguments process_out Standard output process_err Standard error Exit code
References dbg.
void Executor::finished(int exitCode, QProcess::ExitStatus exitStatus)
Executor::finished called when an executed process finishes.
exitCode exitStatus
void Executor::finished(int id, int exitCode, const QString &output, const QString &errout)
finished signal that is emited when process finishes
id id of the process exitCode return code of the process output stdout produced by the process errout stderr produced by the process
void Executor::starting()
starting signal that is emited when process starts
Referenced by Executor, Pass::Pass.
void Executor::error(int id, int exitCode, const QString &output, const QString &errout)
error signal that is emited when process finishes with an error
id id of the process exitCode return code of the process output stdout produced by the process errout stderr produced by the process