QProgressIndicator
int QProgressIndicator::m_angle
int QProgressIndicator::m_timerId
int QProgressIndicator::m_delay
bool QProgressIndicator::m_displayedWhenStopped
QColor QProgressIndicator::m_color
QProgressIndicator::QProgressIndicator(QWidget *parent=nullptr)
QProgressIndicator::QProgressIndicator constructor.
parent widget the indicator is placed in.
int QProgressIndicator::animationDelay() const
Returns the delay between animation steps.
The number of milliseconds between animation steps. By default, the animation delay is set to 40 milliseconds. setAnimationDelay
bool QProgressIndicator::isAnimated() const
Returns a Boolean value indicating whether the component is currently animated.
Animation state. startAnimation stopAnimation
Referenced by paintEvent.
bool QProgressIndicator::isDisplayedWhenStopped() const
Returns a Boolean value indicating whether the receiver shows itself even when it is not animating.
Return true if the progress indicator shows itself even when it is not animating. By default, it returns false. setDisplayedWhenStopped
const QColor & QProgressIndicator::color() const
Returns the color of the component.
setColor
References color.
Referenced by color, paintEvent, setColor.
QSize QProgressIndicator::sizeHint() const
QProgressIndicator::sizeHint default minimum size.
QSize(20, 20)
int QProgressIndicator::heightForWidth(int w) const
QProgressIndicator::heightForWidth square ratio.
w requested width w returned height
void QProgressIndicator::startAnimation()
Starts the spin animation.
stopAnimation isAnimated
void QProgressIndicator::stopAnimation()
Stops the spin animation.
startAnimation isAnimated
void QProgressIndicator::setAnimationDelay(int delay)
Sets the delay between animation steps.
Setting the delay to a value larger than 40 slows the animation, while setting the delay to a smaller value speeds it up. delay The delay, in milliseconds. animationDelay
void QProgressIndicator::setDisplayedWhenStopped(bool state)
Sets whether the component hides itself when it is not animating.
state The animation state. Set false to hide the progress indicator when it is not animating; otherwise true. isDisplayedWhenStopped
void QProgressIndicator::setColor(const QColor &color)
Sets the color of the components to the given color.
color
References color.
void QProgressIndicator::timerEvent(QTimerEvent *event)
QProgressIndicator::timerEvent do the actual animation.
void QProgressIndicator::paintEvent(QPaintEvent *event)
QProgressIndicator::paintEvent draw the spinner.
References color, isAnimated.