SingleApplication
bool SingleApplication::_isRunning
QString SingleApplication::_uniqueKey
QSharedMemory SingleApplication::sharedMemory
QScopedPointer<QLocalServer> SingleApplication::localServer
const int SingleApplication::timeout
SingleApplication::SingleApplication(int &argc, char *argv[], QString uniqueKey)
SingleApplication::SingleApplication this replaces the QApplication allowing for local socket based communications.
argc argv uniqueKey
References receiveMessage, SingleApplication.
Referenced by SingleApplication.
bool SingleApplication::isRunning()
SingleApplication::isRunning is there already a QtPass instance running, to check wether to be server or client.
References isRunning.
Referenced by isRunning, main.
bool SingleApplication::sendMessage(const QString &message)
SingleApplication::sendMessage send a message (from commandline) to an already running QtPass instance.
message
References dbg, sendMessage.
Referenced by main, sendMessage.
void SingleApplication::receiveMessage()
SingleApplication::receiveMessage we have received (a command line) message.
References dbg, messageAvailable, receiveMessage.
Referenced by receiveMessage, SingleApplication.
void SingleApplication::messageAvailable(const QString &message)
messageAvailable notification from commandline
message args sent to qtpass executable
Referenced by receiveMessage.