StoreModel
QFileSystemModel* StoreModel::fs
QString StoreModel::store
bool StoreModel::parseDropData(const QMimeData *data, dragAndDropInfoPasswordStore *outInfo)
bool StoreModel::executeDropAction(const dragAndDropInfoPasswordStore &info, Qt::DropAction action, const QModelIndex &parent)
bool StoreModel::handleDirDrop(const QString &cleanedSrc, const QFileInfo &destFileinfo, const QFileInfo &srcFileInfo, Qt::DropAction action)
bool StoreModel::handleFileDrop(const QString &cleanedSrc, const QString &cleanedDest, const QFileInfo &destFileinfo, Qt::DropAction action)
bool StoreModel::handleFileToDirDrop(const QString &cleanedSrc, const QString &cleanedDest, Qt::DropAction action)
bool StoreModel::handleFileToFileDrop(const QString &cleanedSrc, const QString &cleanedDest, Qt::DropAction action)
StoreModel::StoreModel()
Construct a StoreModel.
StoreModel::StoreModel SubClass of QSortFilterProxyModel via http://www.qtcentre.org/threads/46471-QTreeView-Filter.
bool StoreModel::filterAcceptsRow(int source_row, const QModelIndex &source_parent) const override
Filter whether a row should be displayed.
StoreModel::filterAcceptsRow should row be shown, wrapper for StoreModel::showThis method. source_row Row index in source model. source_parent Parent index in source model. true if row should be displayed. sourceRow sourceParent
References showThis.
bool StoreModel::showThis(const QModelIndex &index) const
Check if a specific index should be shown.
StoreModel::showThis should a row be shown, based on our search criteria. index Model index to check. true if index should be visible. index
References Util::endsWithGpg, showThis.
Referenced by filterAcceptsRow, showThis.
void StoreModel::setModelAndStore(QFileSystemModel *sourceModel, const QString &passStore)
Initialize model with source model and store path.
StoreModel::setModelAndStore update the source model and store. sourceModel Filesystem model to wrap. passStore Root path of password store. sourceModel passStore
void StoreModel::setStore(const QString &passStore)
Update the store path used for filtering without changing the source model.
passStore New root path of password store.
QVariant StoreModel::data(const QModelIndex &index, int role) const override
Get display data for index.
StoreModel::data don't show the .gpg at the end of a file. index Model index. role Data role (e.g., Qt::DisplayRole). Display data for the role. index role
References Util::endsWithGpg.
Referenced by canDropMimeData, dropMimeData.
bool StoreModel::lessThan(const QModelIndex &source_left, const QModelIndex &source_right) const override
Compare two indices for sorting.
StoreModel::lessThan. source_left Left index to compare. source_right Right index to compare. true if left < right. source_left source_right
QString StoreModel::getStore() const
Get the password store root path.
Store path.
Qt::DropActions StoreModel::supportedDropActions() const override
Get supported drop actions.
StoreModel::supportedDropActions enable drop. Supported Qt::DropActions.
Qt::DropActions StoreModel::supportedDragActions() const override
Get supported drag actions.
StoreModel::supportedDragActions enable drag. Supported Qt::DropActions.
Qt::ItemFlags StoreModel::flags(const QModelIndex &index) const override
Get item flags for index.
StoreModel::flags. index Model index. Item flags. index
QStringList StoreModel::mimeTypes() const override
Get supported MIME types for drag/drop.
StoreModel::mimeTypes. List of MIME type strings.
QMimeData *override StoreModel::mimeData(const QModelIndexList &indexes) const
Create MIME data from indexes.
StoreModel::mimeData. indexes List of selected indexes. MIME data object. indexes
References dragAndDropInfoPasswordStore::Directory, dragAndDropInfoPasswordStore::File, dragAndDropInfoPasswordStore::kind, mimeData, dragAndDropInfoPasswordStore::path.
Referenced by mimeData.
bool StoreModel::canDropMimeData(const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const override
Check if drop is possible.
StoreModel::canDropMimeData. data MIME data to drop. action Drop action. row Target row. column Target column. parent Target parent index. true if drop is possible. data action row column parent
References data, dragAndDropInfoPasswordStore::kind.
Referenced by dropMimeData.
bool StoreModel::dropMimeData(const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
Handle dropped MIME data.
StoreModel::dropMimeData. data MIME data to drop. action Drop action. row Target row. column Target column. parent Target parent index. true if drop was handled. data action row column parent
References canDropMimeData, data.