PasswordDialog
Ui::PasswordDialog* PasswordDialog::ui
PasswordConfiguration PasswordDialog::m_passConfig
QStringList PasswordDialog::m_fields
QString PasswordDialog::m_file
bool PasswordDialog::m_templating
bool PasswordDialog::m_allFields
bool PasswordDialog::m_isNew
QList<QLineEdit *> PasswordDialog::templateLines
QList<QLineEdit *> PasswordDialog::otherLines
PasswordDialog::PasswordDialog(PasswordConfiguration passConfig, QWidget *parent=nullptr)
PasswordDialog::PasswordDialog basic constructor.
passConfig configuration constant parent
References Pass::finishedShow, QtPassSettings::getPass, PasswordDialog, setLength, setPass, setPasswordCharTemplate.
Referenced by PasswordDialog, PasswordDialog.
PasswordDialog::PasswordDialog(QString file, const bool &isNew, QWidget *parent=nullptr)
PasswordDialog::PasswordDialog complete constructor.
file isNew parent pointer
References Pass::finishedShow, QtPassSettings::getPass, QtPassSettings::getPassTemplate, QtPassSettings::getPasswordConfiguration, QtPassSettings::isTemplateAllFields, QtPassSettings::isUsePwgen, QtPassSettings::isUseTemplate, PasswordDialog, Pass::processErrorExit, setLength, setPass, setPasswordCharTemplate, setTemplate, templateAll, usePwgen.
PasswordDialog::~PasswordDialog() override
PasswordDialog::~PasswordDialog basic destructor.
void PasswordDialog::setPassword(const QString &password)
Populate the dialog's password field with the given text.
PasswordDialog::setPassword populate the (templated) fields. password Password text to display. getPassword password
References AS_CONST, FileContent::getNamedValues, FileContent::getPassword, FileContent::getRemainingData, FileContent::parse, NamedValues::takeValue.
Referenced by setPass.
QString PasswordDialog::getPassword()
Retrieve the current text from the dialog's password field.
PasswordDialog::getPassword join the (templated) fields to a QString for writing back. Current password as a QString. setPassword collapsed password.
void PasswordDialog::setTemplate(const QString &rawFields, bool useTemplate)
Set the template fields and whether templating is enabled.
PasswordDialog::setTemplate set the template and create the fields. rawFields Template text containing field definitions. useTemplate true to enable the template, false to disable. rawFields
Referenced by PasswordDialog.
void PasswordDialog::templateAll(bool templateAll)
Enable or disable applying the template to all applicable fields.
PasswordDialog::templateAll basic setter for use in PasswordDialog::setPassword templating all tokenisable lines. templateAll true to apply templating to all fields. templateAll
References templateAll.
Referenced by PasswordDialog, templateAll.
void PasswordDialog::setLength(int length)
Set the desired password length shown in the dialog.
PasswordDialog::setLength PasswordDialog::setLength password length. length Desired password length. length
Referenced by PasswordDialog, PasswordDialog.
void PasswordDialog::setPasswordCharTemplate(int templateIndex)
Set the password character template index.
PasswordDialog::setPasswordCharTemplate PasswordDialog::setPasswordCharTemplate chose the template style. templateIndex Index identifying the character template to use. templateIndex
Referenced by PasswordDialog, PasswordDialog.
void PasswordDialog::usePwgen(bool usePwgen)
Enable or disable pwgen-style password generation mode.
PasswordDialog::usePwgen PasswordDialog::usePwgen don't use own password generator. usePwgen true to enable pwgen mode, false to disable. usePwgen
References usePwgen.
Referenced by PasswordDialog, usePwgen.
void PasswordDialog::setPass(const QString &output)
Populate the dialog's password field from pass show output.
Sets the password from pass show output. output Output from the pass show command. output Output from pass show command
References setPassword.
Referenced by PasswordDialog, PasswordDialog.
void PasswordDialog::on_checkBoxShow_stateChanged(int arg1)
PasswordDialog::on_checkBoxShow_stateChanged hide or show passwords.
arg1
void PasswordDialog::on_createPasswordButton_clicked()
PasswordDialog::on_createPasswordButton_clicked generate a random password.
void PasswordDialog::on_accepted()
PasswordDialog::on_accepted handle Ok click for QDialog.
void PasswordDialog::on_rejected()
PasswordDialog::on_rejected handle Cancel click for QDialog.