QtPass
MainWindow* QtPass::m_mainWindow
QProcess QtPass::fusedav
QTimer QtPass::clearClipboardTimer
QString QtPass::clippedText
bool QtPass::freshStart
QtPass::QtPass(MainWindow *mainWindow)
Constructs a QtPass instance.
mainWindow The main window reference
References clearClipboard, setClipboardTimer.
QtPass::~QtPass()
QtPass::~QtPass destroy!
References QtPassSettings::getPassStore, QtPassSettings::isUseWebDav.
bool QtPass::init()
QtPass::init make sure we are ready to go as soon as possible.
References Util::configIsValid, dbg, Util::findPasswordStore, QtPassSettings::getAutoclearPanelSeconds, QtPassSettings::getAutoclearSeconds, QtPassSettings::getPassStore, QtPassSettings::getPassTemplate, QtPassSettings::getPwgenExecutable, QtPassSettings::getVersion, QtPassSettings::initExecutables, QtPassSettings::isUseWebDav, QtPassSettings::setAutoclearPanelSeconds, QtPassSettings::setAutoclearSeconds, QtPassSettings::setPassStore, QtPassSettings::setPassTemplate, QtPassSettings::setUsePwgen, QtPassSettings::setVersion.
void QtPass::setClippedText(const QString &, const QString &p_output=QString())
Sets the text to be stored in clipboard and handles clipboard operations.
password The password or text to store p_output Additional output text
References Enums::CLIPBOARD_ALWAYS, Enums::CLIPBOARD_NEVER, copyTextToClipboard, QtPassSettings::getClipBoardType.
void QtPass::clearClippedText()
Clears the stored clipped text.
void QtPass::setClipboardTimer()
Sets the clipboard clear timer based on autoclear settings.
References QtPassSettings::getAutoclearSeconds, MS_PER_SECOND.
Referenced by QtPass.
bool QtPass::isFreshStart()
void QtPass::setFreshStart(const bool &fs)
void QtPass::setMainWindow()
Sets up the main window and connects signal handlers.
void QtPass::connectPassSignalHandlers(Pass *pass)
Connects pass signal handlers to QtPass slots.
pass The pass instance to connect
void QtPass::mountWebDav()
QtPass::mountWebDav is some scary voodoo magic.
void QtPass::clearClipboard()
MainWindow::clearClipboard remove clipboard contents.
Referenced by QtPass.
void QtPass::copyTextToClipboard(const QString &text)
MainWindow::copyTextToClipboard copies text to your clipboard.
text
References buildClipboardMimeData, QtPassSettings::isUseAutoclear, QtPassSettings::isUseSelection.
Referenced by setClippedText.
void QtPass::showTextAsQRCode(const QString &text)
displays the text as qrcode
text
References createQRCodePopup, QtPassSettings::getQrencodeExecutable.
QDialog * QtPass::createQRCodePopup(const QPixmap &image)
QtPass::createQRCodePopup creates a popup dialog with the given QR code image. This is extracted for testability. The caller is responsible for showing and managing the popup lifecycle.
image The QR code pixmap to display The created popup dialog
Referenced by showTextAsQRCode.
void QtPass::processError(QProcess::ProcessError)
QtPass::processError something went wrong.
error
void QtPass::processErrorExit(int exitCode, const QString &)
Handles process error exit.
exitCode The exit code p_error The error message
void QtPass::processFinished(const QString &, const QString &)
QtPass::processFinished background process has finished.
exitCode exitStatus output stdout from a process errout stderr from a process
void QtPass::passStoreChanged(const QString &, const QString &)
Called when pass store has changed.
p_out Output from the process p_err Error output
void QtPass::passShowHandlerFinished(QString output)
Called when the password show handler has finished.
output The password content to display
void QtPass::doGitPush()
Performs automatic git push if enabled in settings.
void QtPass::finishedInsert(const QString &, const QString &)
Called when an insert operation has finished.
p_output Output from the process p_errout Error output
void QtPass::onKeyGenerationComplete(const QString &p_output, const QString &p_errout)
Called when GPG key generation is complete.
p_output Standard output from the key generation process p_errout Standard error output from the key generation process
void QtPass::showInTextBrowser(QString output, const QString &prefix=QString(), const QString &postfix=QString())
Displays output text in the main window's text browser.
output The text to display prefix Optional prefix to prepend to the output postfix Optional postfix to append to the output