gpgkeystate.cpp
int GPG_MIN_FIELDS
Referenced by handleFprRecord, handlePubSecRecord, parseGpgColonOutput.
int GPG_FIELD_VALIDITY
Referenced by handlePubSecRecord.
int GPG_FIELD_KEY_ID
Referenced by handlePubSecRecord.
int GPG_FIELD_CREATED
Referenced by handlePubSecRecord.
int GPG_FIELD_EXPIRY
Referenced by handlePubSecRecord.
int GPG_FIELD_USERID
Referenced by handleFprRecord, handlePubSecRecord, handleUidRecord.
GpgRecordType classifyRecord(const QString &record_type)
Classify a GPG colon output record type.
record_type The first field of a GPG colon record (e.g., "pub", "sec", "uid") The corresponding GpgRecordType enum value
References Fpr, Grp, Pub, Sec, Ssb, Sub, Uid, Unknown.
Referenced by parseGpgColonOutput.
void handlePubSecRecord(const QStringList &props, bool secret, UserInfo &current_user)
Handle a pub or sec record in GPG colon output.
props The colon-split fields of the record secret True if this is a secret key record (sec) current_user UserInfo to populate with key data
References UserInfo::created, UserInfo::expiry, GPG_FIELD_CREATED, GPG_FIELD_EXPIRY, GPG_FIELD_KEY_ID, GPG_FIELD_USERID, GPG_FIELD_VALIDITY, GPG_MIN_FIELDS, UserInfo::have_secret, UserInfo::key_id, UserInfo::name, UserInfo::validity.
Referenced by parseGpgColonOutput.
void handleUidRecord(const QStringList &props, UserInfo &current_user)
Handle a uid record in GPG colon output.
props The colon-split fields of the record current_user UserInfo to populate with user name
References GPG_FIELD_USERID, UserInfo::name.
Referenced by parseGpgColonOutput.
void handleFprRecord(const QStringList &props, UserInfo &current_user)
Handle an fpr (fingerprint) record in GPG colon output.
props The colon-split fields of the record current_user UserInfo to update with fingerprint if it matches key
References GPG_FIELD_USERID, GPG_MIN_FIELDS, UserInfo::key_id.
Referenced by parseGpgColonOutput.
QList< UserInfo > parseGpgColonOutput(const QString &output, bool secret)
Parse GPG with-colons output into a list of UserInfo.
output Raw output from GPG with-colons with-fingerprint secret True if parsing secret keys (list-secret-keys) QList of parsed UserInfo objects
References classifyRecord, Fpr, GPG_MIN_FIELDS, handleFprRecord, handlePubSecRecord, handleUidRecord, UserInfo::key_id, UserInfo::name, Util::newLinesRegex, Pub, Sec, Uid.
Referenced by Pass::listKeys.