.TH QtPass "1" "Sep 16, 2015"
.SH NAME
qtpass \- GUI for password manager pass
.SH SYNOPSIS
\fBqtpass\fP [directory of the password\-store]
.SH DESCRIPTION
\fBQtPass\fP is a GUI password manager based on pass with the following
 features:
  * Reading pass password stores
  * Decrypting and displaying the password info
  * Updating from the git repository
  * Editing and adding of passwords
  * Adding and removing people from gpg-id per folder
  * Read operations also supported without pass (using gpg and git)
  * Configuration options for backends and executable/folder locations
  * Copying password to clipboard
  * Hiding of password against shouldersurfing
  * Experimental WebDAV support
.SH AUTHOR
This  manual page was written by Philip Rinn <rinni@inventati.org> for the
Debian GNU/Linux system (but may be used by others).
