---
name: QMake
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: {}
jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        qt: [6.8.0]
        include:
          - os: ubuntu-latest
            make: make
            qt: 6.8.0
          - os: macos-latest
            make: make
            qt: 6.8.0
          - os: windows-latest
            make: nmake
            qt: 6.8.0
    steps:
      - uses: actions/checkout@v6
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
      - name: qmake
        run: qmake
      - name: make
        run: ${{matrix.make}}
      - name: make check
        run: ${{matrix.make}} check TESTARGS="--platform offscreen"
