name: publiccode.yml validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      publiccode: ${{ steps.filter.outputs.publiccode }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v4.0.1
        id: filter
        with:
          base: main
          filters: |
            publiccode:
              - "publiccode.yml"

  publiccode_yml_validation:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check if validation needed
        id: need_validation
        shell: bash
        run: |
          if [[ "${NEEDS_CHANGES_OUTPUTS_PUBLICCODE}" == "true" ]] || \
             [[ "${{ github.event_name }}" == "merge_group" ]]; then
            echo "run_validation=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_validation=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          NEEDS_CHANGES_OUTPUTS_PUBLICCODE: ${{ needs.changes.outputs.publiccode }}

      - name: No changes - skipping
        if: steps.need_validation.outputs.run_validation != 'true'
        run: echo "No relevant changes - skipping publiccode validation"

      - uses: actions/checkout@v6.0.2
        if: steps.need_validation.outputs.run_validation == 'true'
        with:
          persist-credentials: false

      - uses: italia/publiccode-parser-action@v1.5.1
        if: steps.need_validation.outputs.run_validation == 'true'
        with:
          publiccode: "publiccode.yml"
