name: publiccode.yml validation

on:
  push:
    branches: ["main"]
    paths:
      - "publiccode.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "publiccode.yml"
  merge_group:

permissions: {}

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: italia/publiccode-parser-action@v1
        with:
          publiccode: "publiccode.yml"
